import { LogAction } from "./LogAction.type";

// French labels for every LogAction value, used by frontends that display
// `app_log` rows (portail-admins activity tab, etc.). Typed on the LogAction
// union so a new backend action will fail to compile here unless its label is
// added. Deprecated actions are kept because old rows still surface in the UI.
export const LOG_ACTION_LABELS: Record<LogAction, string> = {
  REACTIVATION_ACCOUNT: "Réactivation du compte",
  REACTIVATION_STRUCTURE: "Réactivation de la structure",
  BREVO_SYNC: "Synchronisation Brevo",
  STRUCTURE_UPDATE: "Mise à jour de la structure",
  USAGERS_DELETE: "Suppression d'usagers",
  USAGERS_PHONE_UPDATE: "Mise à jour du téléphone usager",
  USAGERS_PHONE_DELETE: "Suppression du téléphone usager",
  USAGERS_EMAIL_UPDATE: "Mise à jour de l'email usager",
  USAGERS_EMAIL_DELETE: "Suppression de l'email usager",
  USAGERS_DOCS_UPLOAD: "Téléversement d'un document usager",
  USAGERS_DOCS_DOWNLOAD: "Téléchargement d'un document usager",
  USAGERS_DOCS_DELETE: "Suppression d'un document usager",
  USAGERS_DOCS_RENAME: "Renommage d'un document usager",
  USAGERS_DOCS_SHARED: "Partage d'un document usager",
  USAGERS_PATCH_SMS_PHONE_NUMBER: "Modification du téléphone SMS usager",
  USAGERS_PATCH_EMAIL: "Modification de l'email usager",
  USAGERS_ENABLE_SMS: "Activation des SMS usager",
  USAGERS_DISABLE_SMS: "Désactivation des SMS usager",
  MON_DOMIFA_DOWNLOAD_DOC: "Téléchargement d'un document Mon DomiFa",
  MON_DOMIFA_DOWNLOAD_DOC_TRY: "Tentative de téléchargement Mon DomiFa",
  MON_DOMIFA_CREATE_PORTAIL_ACCOUNT_BULK: "Création de comptes portail (bulk)",
  EXPORT_USAGERS: "Export des usagers",
  GET_STATS: "Consultation des statistiques",
  EXPORT_STATS: "Export des statistiques",
  EXPORT_STATS_FROM_ADMIN: "Export des statistiques (admin)",
  ENABLE_SMS_BY_STRUCTURE: "Activation des SMS (structure)",
  DISABLE_SMS_BY_STRUCTURE: "Désactivation des SMS (structure)",
  SMS_SETTINGS_UPDATE: "Mise à jour des paramètres SMS",
  EXPORT_DOMIFA: "Export DomiFa",
  GET_STATS_PORTAIL_ADMIN: "Consultation des statistiques (pilotage)",
  GET_STATS_PORTAIL_ADMIN_DENIED: "Accès statistiques refusé",
  EXPORT_STATS_PORTAIL_ADMIN: "Export des statistiques (pilotage)",
  IMPORT_USAGERS_SUCCESS: "Import d'usagers réussi",
  IMPORT_USAGERS_PREVIEW: "Aperçu d'import d'usagers",
  IMPORT_USAGERS_FAILED: "Import d'usagers échoué",
  IMPORT_TEMPLATE_DOWNLOAD: "Téléchargement du modèle d'import",
  IMPORT_DOWNLOAD_GUIDE: "Téléchargement du guide d'import",
  USER_ROLE_CHANGE: "Changement de rôle",
  USER_CREATE: "Création d'un utilisateur",
  USER_DELETE: "Suppression d'un utilisateur",
  ADMIN_CREATE_USER_STRUCTURE: "Création d'un utilisateur de structure",
  ADMIN_CREATE_USER_SUPERVISOR: "Création d'un utilisateur pilotage",
  ADMIN_PATCH_USER_SUPERVISOR: "Modification d'un utilisateur pilotage",
  ADMIN_DELETE_USER_SUPERVISOR: "Suppression d'un utilisateur pilotage",
  ADMIN_ELEVATE_ROLE_USER_SUPERVISOR: "Promotion en administrateur",
  ADMIN_USER_ROLE_CHANGE: "Changement de rôle utilisateur",
  ADMIN_USER_CREATE: "Création d'un utilisateur",
  ADMIN_USER_DELETE: "Suppression d'un utilisateur",
  ADMIN_PASSWORD_RESET: "Réinitialisation de mot de passe (admin)",
  ADMIN_STRUCTURE_VALIDATE: "Validation d'une structure",
  ADMIN_STRUCTURE_DELETE: "Suppression d'une structure",
  ADMIN_STRUCTURE_REFUSAL: "Refus d'une structure",
  ADMIN_STRUCTURE_CREATION: "Création d'une structure",
  SUPPRIMER_PIECE_JOINTE: "Suppression d'une pièce jointe",
  RESET_PASSWORD_PORTAIL: "Réinitialisation du mot de passe portail",
  DOWNLOAD_PASSWORD_PORTAIL: "Téléchargement du mot de passe portail",
  DELETE_NOTE: "Suppression d'une note",
  ENABLE_PORTAIL_BY_STRUCTURE: "Activation du portail (structure)",
  DISABLE_PORTAIL_BY_STRUCTURE: "Désactivation du portail (structure)",
  THROTTLE_BLOCKED: "Quota de requêtes dépassé",
  REQUEST_BLOCKED: "Requête bloquée",
  UNBLOCK_USER: "Déblocage d'un utilisateur",
  BLOCK_USER: "Blocage automatique d'un utilisateur",
  BLOCK_USER_BY_ADMIN: "Blocage manuel d'un utilisateur",
  ACCESS_DENIED_NON_ACTIVE: "Accès refusé (compte non actif)",
  UNBLOCK_BREVO_CONTACT: "Déblocage du contact Brevo",
};

export function getLogActionLabel(action: string): string {
  return LOG_ACTION_LABELS[action as LogAction] ?? action;
}
