import { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faComment,
  faEdit,
  faEye,
  faEyeSlash,
  faFileWord,
} from "@fortawesome/free-regular-svg-icons";
import {
  faBars,
  faChartBar,
  faCheck,
  faCircleNotch,
  faDownload,
  faExclamationCircle,
  faInfoCircle,
  faListAlt,
  faSearch,
  faSignInAlt,
  faCheckCircle,
  faTimesCircle,
  faSignOutAlt,
  faSort,
  faTimes,
  faTrash,
  faUserPlus,
  faExclamationTriangle,
  faSpinner,
  faArrowUpRightFromSquare,
  faExternalLinkAlt,
} from "@fortawesome/free-solid-svg-icons";

export const FA_ICONS: IconDefinition[] = [
  faDownload,
  faEdit,
  faEye,
  faEyeSlash,
  faFileWord,
  faCheckCircle,
  faExclamationCircle,
  faExclamationTriangle,
  faTimesCircle,
  faInfoCircle,
  faUserPlus,
  faCircleNotch,
  faArrowUpRightFromSquare,
  faComment,
  faSignInAlt,
  faCheck,
  faTimes,
  faBars,
  faTrash,
  faDownload,
  faSort,
  faListAlt,
  faChartBar,
  faSignOutAlt,
  faSearch,
  faExternalLinkAlt,
  faSpinner,
];
