export const USAGERS_IMPORT_COLUMNS = {
  customId: { index: 0, label: "Numéro d'identification" },
  civilite: { index: 1, label: "Civilité" },
  nom: { index: 2, label: "Nom" },
  prenom: { index: 3, label: "Prénom" },
  surnom: { index: 4, label: "Nom d'usage / Surnom" },
  dateNaissance: { index: 5, label: "Date naissance" },
  lieuNaissance: { index: 6, label: "Lieu naissance" },
  phone: { index: 7, label: "Téléphone" },
  email: { index: 8, label: "Email" },
  statutDom: { index: 9, label: "Statut domiciliation" },
  motifRefus: { index: 10, label: "Motif de refus" },
  motifRadiation: { index: 11, label: "Motif de radiation" },
  typeDom: { index: 12, label: "Type de domiciliation" },
  dateDebutDom: { index: 13, label: "Date de Début de la domiciliation" },
  dateFinDom: { index: 14, label: "Date de fin de la domiciliation" },
  datePremiereDom: { index: 15, label: "Date 1ere domiciliation" },
  dateDernierPassage: { index: 16, label: "Date de dernier passage" },
  orientation: { index: 17, label: "Orientation" },
  orientationDetails: { index: 18, label: "Détails de l'orientation" },
  domiciliationExistante: {
    index: 19,
    label: "La personne a t-elle déjà une domiciliation ?",
  },
  revenus: { index: 20, label: "Le domicilié possède t-il des revenus ?" },
  revenusDetails: {
    index: 21,
    label: "Seulement si revenus, de quelle nature ?",
  },
  lienCommune: { index: 22, label: "Lien avec la commune" },
  compositionMenage: { index: 23, label: "Composition du ménage" },
  situationResidentielle: { index: 24, label: "Situation résidentielle" },
  situationDetails: {
    index: 25,
    label: "Si autre situation résidentielle, précisez",
  },
  causeInstabilite: { index: 26, label: "Cause instabilité logement" },
  causeDetails: { index: 27, label: "Si autre cause, précisez" },
  raisonDemande: { index: 28, label: "Motif principal de la demande" },
  raisonDemande_details: { index: 29, label: "Si autre motif, précisez" },
  accompagnement: { index: 30, label: "Accompagnement social" },
  accompagnementDetails: {
    index: 31,
    label: "Par quelle structure est fait l'accompagnement ?",
  },
  commentaires: { index: 32, label: "Commentaires" },
};
