export const USAGERS_IMPORT_COLUMNS = {
  CUSTOM_ID: { index: 0, label: "Numéro d'identification" },
  civilite: { index: 1, label: "Civilité" },
  NOM: { index: 2, label: "Nom" },
  PRENOM: { index: 3, label: "Prénom" },
  SURNOM: { index: 4, label: "Nom d'usage / Surnom" },
  DATE_NAISSANCE: { index: 5, label: "Date naissance" },
  LIEU_NAISSANCE: { index: 6, label: "Lieu naissance" },
  PHONE: { index: 7, label: "Téléphone" },
  EMAIL: { index: 8, label: "Email" },
  STATUT_DOM: { index: 9, label: "Statut domiciliation" },
  MOTIF_REFUS: { index: 10, label: "Motif de refus" },
  MOTIF_RADIATION: { index: 11, label: "Motif de radiation" },
  TYPE_DOM: { index: 12, label: "Type de domiciliation" },
  DATE_DEBUT_DOM: { index: 13, label: "Date de Début de la domiciliation" },
  DATE_FIN_DOM: { index: 14, label: "Date de fin de la domiciliation" },
  DATE_PREMIERE_DOM: { index: 15, label: "Date 1ere domiciliation" },
  DATE_DERNIER_PASSAGE: { index: 16, label: "Date de dernier passage" },
  ORIENTATION: { index: 17, label: "Orientation" },
  ORIENTATION_DETAILS: { index: 18, label: "Détails de l'orientation" },
  DOMICILIATION_EXISTANTE: {
    index: 19,
    label: "La personne a t-elle déjà une domiciliation ?",
  },
  REVENUS: { index: 20, label: "Le domicilié possède t-il des revenus ?" },
  REVENUS_DETAILS: {
    index: 21,
    label: "Seulement si revenus, de quelle nature ?",
  },
  LIEN_COMMUNE: { index: 22, label: "Lien avec la commune" },
  COMPOSITION_MENAGE: { index: 23, label: "Composition du ménage" },
  SITUATION_RESIDENTIELLE: { index: 24, label: "Situation résidentielle" },
  SITUATION_DETAILS: {
    index: 25,
    label: "Si autre situation résidentielle, précisez",
  },
  CAUSE_INSTABILITE: { index: 26, label: "Cause instabilité logement" },
  CAUSE_DETAILS: { index: 27, label: "Si autre cause, précisez" },
  RAISON_DEMANDE: { index: 28, label: "Motif principal de la demande" },
  RAISON_DEMANDE_DETAILS: { index: 29, label: "Si autre motif, précisez" },
  ACCOMPAGNEMENT: { index: 30, label: "Accompagnement social" },
  ACCOMPAGNEMENT_DETAILS: {
    index: 31,
    label: "Par quelle structure est fait l'accompagnement ?",
  },
  COMMENTAIRES: { index: 32, label: "Commentaires" },
  // AYANT_DROIT: {index:  [33, 37, 41, 45, 49, 53, 57, 61, 65], label: ''},

  // "Ayant-droit 1: nom",
  // "Ayant-droit 1: prénom",
  // "Ayant-droit 1: date naissance",
  // "Ayant-droit 1: lien parenté",
  // "Ayant-droit 2: nom",
  // "Ayant-droit 2: prénom",
  // "Ayant-droit 2: date naissance",
  // "Ayant-droit 2: lien parenté",
  // "Ayant-droit 3: nom",
  // "Ayant-droit 3: prénom",
  // "Ayant-droit 3: date naissance",
  // "Ayant-droit 3: lien parenté",
  // "Ayant-droit 4: nom",
  // "Ayant-droit 4: prénom",
  // "Ayant-droit 4: date de naissance",
  // "Ayant-droit 4: lien parenté",
};
