version: "3.4"

services:
  postgres:
    image: postgres:10.14 # https://hub.docker.com/_/postgres
    container_name: domifa-postgres-test
    volumes:
      # /docker-entrypoint-initdb.d/*.(sh|js) are automatically run on startup
      - ./_scripts/docker/postgres-restore-dump.docker-entrypoint.sh:/docker-entrypoint-initdb.d/postgres-restore-dump.docker-entrypoint.sh
      - ./_scripts:/app/_scripts:delegated
    ports:
      - "5433:5432"
    environment:
      TZ: UTC
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env.test.travis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s
