export const MESSAGE_SMS_RESPONSE_ERRORS = {
  1: "Type de message non spécifié ou incorrect",
  2: "Le message est vide",
  3: "Le message contient plus de 160 caractères",
  4: "Aucun destinataire valide n'est renseigné",
  5: "Numéro interdit",
  6: "Numéro de destinataire invalide",
  7: "Votre compte n'a pas de formule définie",
  8: "SMS | L'expéditeur est invalide.",
  9: "Le système a rencontré une erreur, merci de nous contacter.",
  10: "Vous ne disposez pas d'assez de crédits pour effectuer cet envoi.",
  11: "L'envoi des message est désactivé pour la démonstration.",
  12: "Votre compte a été suspendu. Contactez-nous pour plus d'informations",
  13: "Votre limite d'envoi paramétrée est atteinte. Contactez-nous pour plus d'informations,",
  14: "Votre limite d'envoi paramétrée est atteinte. Contactez-nous pour plus d'informations,",
  15: "Votre limite d'envoi paramétrée est atteinte. Contactez-nous pour plus d'informations,",
  16: "Le paramètr -smslongnbr- n'est pas cohérent avec la taille du message envoyé.",
  17: "L'expéditeur n'est pas autorisé.",
  21: "Token invalide. Contactez-nous pour plus d'informations.",
  22: "Durée du message non autorisée. Contactez-nous pour plus d'informations.",
  23: "Aucune date variable valide n'a été trouvée dans votre liste de destinataires.",
  24: "Votre campagne n'a pas été validée car il manque la mention « STOP » dans votre message. ",
  30: "Clé API non reconnue.",
  36: "Vous ne pouvez pas avoir d'emojis dans votre message.",
  38: "Vous devez ajouter une mention STOP à votre SMS.",
  50: "Le fuseau horaire spécifié n'est pas valide.",
  53: "Nous limitons à 5 pièces jointes par campagne email.",
  99: "Votre compte est suspendu.",
};
