export const MESSAGE_SMS_RESPONSE_ERRORS = {
  1: "Invalid login or un-authorized API usage",
  2: "Consumer is blocked by Netsize",
  3: "Operation is not provisioned by Netsize",
  4: "The consumer is unknown to Netsize",
  5: "Consumer has blocked this service in Netsize",
  6: "The originating address is not supported",
  7: "Alpha originating address not supported by account",
  8: "MSISDN originating address not supported",
  9: "GSM extended not supported",
  10: "Unicode not supported",
  11: "Status report not supported",
  12: "Required capability not supported",
  13: "The content provider max throttling rate is exceeded",
  14: "Protocol ID not supported by account",
  15: "Message concatenation limit exceeded",
  16: "Unable to route message.",
  17: "Prohibited time period",
  18: "Too low balance on service provider account",
  50: "Partial success",
  99: "Internal server error",
  100: "Invalid destination address",
  102: "Invalid referenced (linked) ID",
  103: "Invalid account name",
  105: "Invalid service meta data",
  106: "Invalid originating address",
  107: "Invalid alphanumeric originating address",
  108: "Invalid validity time",
  109: "Invalid delivery time",
  110: "Invalid message content/user data",
  111: "Invalid message length",
  112: "Invalid user data header",
  113: "Invalid data coding scheme",
  114: "Invalid protocol ID",
  115: "Invalid status report flags",
  116: "Invalid TON",
  117: "Invalid campaign name",
  120: "Invalid limit for maximum number of concatenated messages",
  121: "Invalid msisdn originating address",
  122: "Invalid correlation ID",
};
