import { StructureCommon } from "@domifa/common";

export const STRUCTURE_COMMON_ATTRIBUTES: (keyof StructureCommon)[] = [
  "uuid",
  "id",
  "adresse",
  "complementAdresse",
  "nom",
  "structureType",
  "ville",
  "departement",
  "region",
  "capacite",
  "codePostal",
  "agrement",
  "telephone",
  "email",
  "responsable",
  "options",
  "adresseCourrier",
  "sms",
  "lastLogin",
  "timeZone",
  "portailUsager",
];
