kind: ConfigMap
apiVersion: v1
metadata:
  name: backend-configmap
data:
  DOMIFA_ENV_ID: prod
  DOMIFA_ENV_PRESET: dist-prod.preset.env
  PGSSLMODE: "require"
  NODE_ENV: production
  DOMIFA_PRINT_CONFIG: "false"
  DOMIFA_EMAILS_ENABLE: "true"
  DOMIFA_SMS_ENABLED: "true"
  POSTGRES_SSL: "true"
  # 50 connexions max : https://docs.microsoft.com/fr-fr/azure/postgresql/concepts-limits
  POSTGRES_POOL_MAX_CONNEXIONS: "100"
  DOMIFA_FRONTEND_META_ROBOTS: index,follow
  DOMIFA_LOG_HTTP_REQUESTS: "true"
  DOMIFA_LOG_SQL_REQUESTS: "false"
