#

.base_docker_image_stage:
  image: docker:$DOCKER_VERSION
  services:
    - docker:$DOCKER_VERSION-dind

#

.base_docker_kube_image_stage:
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/kubectl:0.11.1
  before_script:
    - source ./.gitlab-ci/env.sh
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}

.base_docker_helm_image_stage:
  extends: .base_docker_kube_image_stage
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/helm:0.11.1

#

.base_register_stage:
  extends: .base_docker_image_stage
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
  script:
    - >
      if [[ -n "${CI_COMMIT_TAG}" ]]; then
        export TAG=$(printf "${CI_COMMIT_TAG}" | sed "s/^v//")
      else
        export TAG=$CI_COMMIT_REF_SLUG
      fi
    #
    - docker pull $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA || true
    - docker pull $IMAGE_NAME:$TAG || true
    - docker pull $IMAGE_NAME:master || true
    - echo "> docker build $DOCKER_BUILD_ARGS --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA --cache-from $IMAGE_NAME:$TAG --cache-from $IMAGE_NAME:master -t $IMAGE_NAME:$CI_COMMIT_SHA -t $IMAGE_NAME:$TAG $CONTEXT"
    - docker build $DOCKER_BUILD_ARGS --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA --cache-from $IMAGE_NAME:$TAG --cache-from $IMAGE_NAME:master -t $IMAGE_NAME:$CI_COMMIT_SHA -t $IMAGE_NAME:$TAG $CONTEXT
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:$TAG
