# Default values for Mas webapp. https://github.com/SocialGouv/helm-charts/blob/master/webapp/values.yaml
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ${CI_REGISTRY_IMAGE}/backend
  tag: ${IMAGE_TAG}

deployment:
  port: ${PORT}
  resources:
    requests:
      cpu: 5m
      memory: 16Mi
    limits:
      cpu: 50m
      memory: 32Mi
service:
  port: ${PORT}

certificate:
  clusterIssuer: ${LETSENCRYPT_ISSUER}
ingress:
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
  - ${API_HOST}
  tls:
  - secretName: ${APP_NAME}-crt-secret${HASH_BRANCH_NAME}
    hosts:
    - ${API_HOST}
