export type DomifaEnv = {
  DOMIFA_ENV_PRESET: string;
  DOMIFA_ENV_PRIORITY: "files" | "process.env";
  DOMIFA_SECURITY_FILES_MAIN_SECRET: string;
  DOMIFA_FRONTEND_URL: string;
  DOMIFA_PORTAIL_USAGERS_URL: string;
  DOMIFA_PORTAIL_ADMINS_URL: string;
  DOMIFA_BACKEND_URL: string;
  DOMIFA_SECURITY_JWT_SECRET: string;

  // S3
  S3_BUCKET_ACCESS_KEY: string;
  S3_BUCKET_SECRET_KEY: string;
  S3_BUCKET_ENDPOINT: string;
  S3_BUCKET_NAME: string;
  S3_BUCKET_REGION: string;
  S3_BUCKET_ROOT_DIR: string;

  DOMIFA_ENV_ID: string;
  DOMIFA_VERSION: string;
  DOMIFA_SWAGGER_ENABLE: string;
  DOMIFA_EMAILS_ENABLE: string;
  DOMIFA_ADMIN_EMAIL: string;
  DOMIFA_EMAIL_ADDRESS_REDIRECT_ALL_TO: string;
  DOMIFA_ERROR_REPORT_EMAILS: string; // @deprecated
  DOMIFA_CRON_ENABLED: string;
  DOMIFA_ANONYMIZER_PASSWORD: string;
  POSTGRES_HOST: string;
  POSTGRES_PORT: string;
  POSTGRES_USERNAME: string;
  POSTGRES_PASSWORD: string;
  POSTGRES_DATABASE: string;
  POSTGRES_SSL: boolean;
  DOMIFA_TYPEORM_RUN_ON_STARTUP: string;

  DOMIFA_MAIL_BREVO_API_KEY: string;
  DOMIFA_MAIL_BREVO_CONTACTS_USERS_LIST_ID: string;
  DOMIFA_MAIL_BREVO_CONTACTS_STRUCTURES_LIST_ID: string;
  // Brevo email templates
  DOMIFA_BREVO_TEMPLATES_CONTACT_FORM: string;
  DOMIFA_BREVO_TEMPLATES_USER_RESET_PASSWORD: string;
  DOMIFA_BREVO_TEMPLATES_USER_STRUCTURE_APPOINTMENT_CREATED: string;
  DOMIFA_BREVO_TEMPLATES_HARD_RESET: string;
  DOMIFA_BREVO_TEMPLATES_USER_ACCOUNT_ACTIVATED: string;
  DOMIFA_BREVO_TEMPLATES_STRUCTURE_REFUSAL: string;
  DOMIFA_BREVO_TEMPLATES_STRUCTURE_DELETE: string;
  DOMIFA_BREVO_TEMPLATES_USER_ACCOUNT_CREATED_BY_ADMIN: string;
  DOMIFA_BREVO_TEMPLATES_STRUCTURE_PENDING_ACTIVATION: string;
  DOMIFA_BREVO_TEMPLATES_IMPORT_FAIL: string;
  DOMIFA_SENTRY_ENABLED: string;
  DOMIFA_SENTRY_DEBUG_MODE_ENABLED: string;
  DOMIFA_SENTRY_DSN_BACKEND: string;
  DOMIFA_LOG_HTTP_REQUESTS: string;
  DOMIFA_LOG_SQL_REQUESTS: string;
  DOMIFA_SMS_ENABLE: string;
  DOMIFA_SMS_API_KEY: string;
  DOMIFA_ENV_PRESET_PARENT: string;
  DOMIFA_PHONE_NUMBER_REDIRECT_ALL_TO: string;
  SOLIGUIDE_URL: string;
  SOLIGUIDE_TOKEN: string;
  MSS_URL: string;
  MSS_TOKEN: string;
  DATA_INCLUSION_URL: string;
  DATA_INCLUSION_TOKEN: string;
  METABASE_TOKEN: string;
  METABASE_URL: string;
};
