import { PortailUsagerUsager } from "../../../../_common/model";

export const USAGER_PORTAIL_ATTRIBUTES: (keyof PortailUsagerUsager)[] = [
  "uuid",
  "ref",
  "customRef",
  "structureId",
  "nom",
  "prenom",
  "surnom",
  "sexe",
  "dateNaissance",
  "email",
  "decision",
  "datePremiereDom",
  "typeDom",
  "etapeDemande",
  "rdv",
  "lastInteraction",
  "options",
  "historique",
  "ayantsDroits",
  "telephone",
  "contactByPhone",
];
