import { Usager } from "@domifa/common";

export const USAGER_LIGHT_ATTRIBUTES: (keyof Usager)[] = [
  "uuid",
  "ref",
  "customRef",
  //"structureId",
  "nom",
  "prenom",
  "surnom",
  "sexe",
  "dateNaissance",
  // "email",
  "decision",
  // "datePremiereDom",
  "statut",
  "typeDom",
  "pinnedNote",
  // "entretien",
  "etapeDemande",
  "rdv",
  // "numeroDistribution",
  "lastInteraction",
  "options",
  "historique",
  "ayantsDroits",
  //"villeNaissance",
  "telephone",
  // "langue",
  // "contactByPhone",
];
