pg:
  # this force ce PG cluster to be destroyed on redeploys
  ~preDeploy.cleaner:
    match:
      kind: Cluster
    value: true

jobs:
  runs:
    build-backend:
      with:
        buildArgs:
          DOMIFA_BACKEND_URL: https://api-{{ .Values.global.host }}/
          DOMIFA_PORTAIL_ADMINS_URL: https://admin-{{ .Values.global.host }}/
          DOMIFA_PORTAIL_USAGERS_URL: https://mon-{{ .Values.global.host }}/
          DOMIFA_FRONTEND_URL: https://{{ .Values.global.host }}/
    seed:
      ~needs: [backend-cron] # need backend to run migrations
      use: seed-db
      with:
        seedPath: _scripts/db/dumps/domifa_test.postgres.truncate-restore-data-only.sql

backend: &backendDev
  ~needs: [build-backend, pg]
  env: &backendEnv
    - name: S3_BUCKET_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_endpoint
    - name: S3_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_name
    - name: S3_BUCKET_REGION
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_region
    - name: S3_BUCKET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_access_key
    - name: S3_BUCKET_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_secret_key
    - name: S3_BUCKET_ROOT_DIR
      value: review-branch/{{ .Values.global.branchSlug32  }}/files

backend-export:
  <<: *backendDev
  ~needs: [build-backend, pg]
  ingress:
    paths:
      - /export
      - /admin/structures/export
      - /stats
      - /stats/home

backend-cron:
  ~needs: [build-backend, pg]
  env: *backendEnv
