pg:
  ~chart: pg
  cnpg-cluster:
    annotations:
      oblik.socialgouv.io/enabled: "false"
      ressource.socialgouv.io/enforced: "true"
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
    persistence:
      size: 20Gi
  # this force ce PG cluster to be destroyed on redeploys
  ~preDeploy.cleaner:
    match:
      kind: Cluster
    value: false

jobs:
  runs:
    seed:
      ~needs: [backend-cron] # need backend to run migrations
      use: seed-db
      with:
        seedPath: _scripts/db/dumps/domifa_test.postgres.truncate-restore-data-only.sql

backend: &backendDev
  ~needs: [pg]
  env: &backendEnv
    - name: S3_BUCKET_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_endpoint
    - name: S3_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_name
    - name: S3_BUCKET_REGION
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_region
    - name: S3_BUCKET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_access_key
    - name: S3_BUCKET_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_secret_key
    - name: S3_BUCKET_ROOT_DIR
      value: review-branch/{{ .Values.global.branchSlug32  }}/files

backend-export:
  <<: *backendDev
  ~needs: [pg]
  ingress:
    paths:
      - /export
      - /admin/structures/export
      - /stats
      - /stats/home

backend-cron:
  ~needs: [pg]
  env: *backendEnv
