pg:
  # this force ce PG cluster to be destroyed on redeploys
  ~preDeploy.cleaner:
    match:
      kind: Cluster
    value: true

jobs:
  runs:
    build-backend:
      with:
        buildArgs:
          DOMIFA_BACKEND_URL: https://api-{{ .Values.global.host }}/
          DOMIFA_PORTAIL_ADMINS_URL: https://admin-{{ .Values.global.host }}/
          DOMIFA_PORTAIL_USAGERS_URL: https://mon-{{ .Values.global.host }}/
          DOMIFA_FRONTEND_URL: https://{{ .Values.global.host }}/
    seed:
      ~needs: [backend] # need backend to run migrations
      use: seed-db
      with:
        seedPath: _scripts/db/dumps/domifa_test.postgres.truncate-restore-data-only.sql

backend:
  ~needs: [build-backend, pg]
  volumes:
    - name: files
      emptyDir: {}
  volumeMounts:
    - mountPath: /mnt/files
      name: files
  vars:
    S3_BUCKET_ROOT_DIR: /dev/{{ .Values.global.branchSlug32  }}/files

backend-cron:
  ~needs: [backend]
  vars:
    S3_BUCKET_ROOT_DIR: /dev/{{ .Values.global.branchSlug32  }}/files
