jobs:
  runs:
    build-backend:
      with:
        buildArgs:
          DOMIFA_BACKEND_URL: https://api-{{ .Values.global.host }}/
          DOMIFA_PORTAIL_ADMINS_URL: https://admin-{{ .Values.global.host }}/
          DOMIFA_PORTAIL_USAGERS_URL: https://mon-{{ .Values.global.host }}/
          DOMIFA_FRONTEND_URL: https://{{ .Values.global.host }}/

    drop-db:
      use: drop-db
      with:
        pgAdminUserSecretRefName: azure-pg-admin-user-devflex
    create-db:
      ~needs: [drop-db]
      use: create-db
      with:
        pgAdminUserSecretRefName: azure-pg-admin-user-devflex
        useAzureFlex: "true"
    seed:
      ~needs: [backend]
      use: seed-db
      with:
        seedPath: _scripts/db/dumps/domifa_test.postgres.truncate-restore-data-only.sql

backend:
  ~needs: [create-db]
  volumes:
    - name: files
      emptyDir: {}
  volumeMounts:
    - mountPath: /mnt/files
      name: files

backend-cron:
  ~needs: [create-db]
