global:
  pgSecretName: pg-app

jobs:
  runs:
    build-backend:
      with:
        buildArgs:
          DOMIFA_BACKEND_URL: https://api-{{ .Values.global.host }}/
          DOMIFA_PORTAIL_ADMINS_URL: https://admin-{{ .Values.global.host }}/
          DOMIFA_PORTAIL_USAGERS_URL: https://mon-{{ .Values.global.host }}/
          DOMIFA_FRONTEND_URL: https://{{ .Values.global.host }}/

    seed:
      ~needs: [backend, pg]
      use: seed-db
      with:
        seedPath: _scripts/db/dumps/domifa_test.postgres.truncate-restore-data-only.sql

backend:
  ~needs: [build-backend]
  volumes:
    - name: files
      emptyDir: {}
  volumeMounts:
    - mountPath: /mnt/files
      name: files

backend-cron:
  ~needs: [build-backend]
