global:
  pgSecretName: pg-app
  pgDatabase: preprod
  pgUser: preprod

pg:
  ~chart: pg
  cnpg-cluster:
    persistence:
      size: "200Gi"
    resources:
      requests:
        memory: 3Gi
      limits:
        memory: 3Gi
    recovery:
      enabled: true
      ~tpl~database: "{{ .Values.global.pgDatabase }}"
      ~tpl~owner: "{{ .Values.global.pgUser }}"
      secretName: "pg-db"
      barmanObjectStore:
        ~tpl~destinationPath: "s3://domifa-dev-backups/domifa-preprod"
        s3Credentials:
          accessKeyId:
            ~tpl~name: "domifa-dev-backups-access-key"
            key: bucket_access_key
          secretAccessKey:
            ~tpl~name: "domifa-dev-backups-access-key"
            key: bucket_secret_key
          region:
            ~tpl~name: "domifa-dev-backups-access-key"
            key: bucket_region

jobs:
  runs:
    build-backend:
      with:
        buildArgs:
          DOMIFA_BACKEND_URL: https://api-{{ .Values.global.host }}/
          DOMIFA_PORTAIL_ADMINS_URL: https://admin-{{ .Values.global.host }}/
          DOMIFA_PORTAIL_USAGERS_URL: https://mon-{{ .Values.global.host }}/
          DOMIFA_FRONTEND_URL: https://{{ .Values.global.host }}/
    seed:
      ~needs: [backend] # need backend to run migrations
      use: seed-db
      with:
        seedPath: _scripts/db/dumps/domifa_test.postgres.truncate-restore-data-only.sql

backend:
  ~needs: [build-backend, pg]
  volumes:
    - name: files
      emptyDir: {}
  volumeMounts:
    - mountPath: /mnt/files
      name: files

backend-cron:
  ~needs: [backend]
