apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: metabase
  namespace: domifa-preprod
spec:
  encryptedData:
    MB_ENCRYPTION_SECRET_KEY: AgCTPgOzPo+WifYELzAwAY31riRGrqoziMUlBSe5r15FPFt1Jh036ia4+ylZXlCwYnwsPOFWftuPFdZW107O/FG9/DkLnT6VuI+R9AHLKrugTtE3DVQftI1YMSR1phVslbaAnRvfX3GRUhf1EFGXRhTupo/hpOTPGIC2dkNxCuPL6QWpi0tzqS1K74ANomNFhTAS5fcr8t7E0wajpwN+1mKOoKxoAHovL3ARjHSypLSrJd8xEkept4RbuQt0JTaWWnEOW5UNUkgWIJHXo24Uea8eiZXkMZ2tVyo8CDyznNiL+bqdODANiK/SKZ4fafP5qL9pibo5pZzEZW6C1xE+CHXzpoej3+G7KZdi0e5yk8+QbqTncHT1DcjcLUdW7wXU45TbzWWU/1ikgcwrTtTRm0SgIqzyGoEexiPxtvtPq895ZCouRPxhm6kI2jgz9fboYTDY4Hdn5zSc/S/Vg3s9scirCkRIutVOycHsIxlgx9pGU2KbgKpteXaCn9i8FT84/raN1ZKXNt7xz5t6ZEDNRwa5XtX1WoLn+Od5Mujoe589Xlve05nusdqfcmCElqe5RJ5PRQ0F+MYIZtdV547k4VENcPS8ZnxFLaDvaTCOtbS529GPHW/mpOATOjv6vW3OeIS3YxeRUjDUcAU71f5GL4xCWZnbIslSkcciLljVtpDrJR5ai+Mg/9SkaPPQ8aA78KvQnejIpvdw1RPKYnDIJZG0EgqGq+gzZsBPIzOxQ2U=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: metabase
    type: Opaque
