apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: metabase
  namespace: domifa-preprod
spec:
  encryptedData:
    MB_DB_CONNECTION_URI: AgCAq9F+U+gEcZN4S8C1lUuVbM5jorWWXWapc2qdnIfXP475jA2k3/fDNDBGjwDK53/3mD1f+liOp4+EVE9RNO7iC776bVyV6X9TU8G9DDNLW48utwn/s//NSkz+SapGZVoWc615QFE5dCDdBTn66Vs8DyiiE8AVY+e/Oxh0wIDgD+wgZqE7oc5edEy2t2qAHbBCJS2i8QWxy4QSxRg1ii/Om9XQCQO11bAaFetUu/3QmtGddkHVX2tdu1a41V0uP1lAmrN7acV2xcO43wMPpPkgpLxppyhNK2P0+8vUucuED08PJOiJAqSgqHwQmhFrnfRYpCyN6K9uYUEd+nvtpyz09I6JQVICxIe3xtsEXkvVtplTNJw3Ak/JZ+wA3hOkNc1dlpMpBZ5hGhnWN9RRBIlKPGqvS97hWyLg246idSyNNiuCZGZVht13kg0YrlQEic+W+TOo/8MvM/4H/lK3b0zbqHiSrnvvOxDihwow93GYyZ05MFkb+ZE4VgXnT4YyeJzi6n1y+2wNfZN2dpvEEfMuzucJ62OnvGHpe++XrhhXPWt58Po7uczfzsM1CihPwmmzJGJ491H3k69R4CAJ7xfXLXoDg92ZvEG9OGRed71EAtqdlqAPHAj40U7xpWTSBnEdfTFq6o2zDOMRJuT1alYWJG1qM/fEQI3s+G2piSzTku3SGPUJ0tHEcAfMfHNVHuxoUIQ0/JFP9Ec9ttZztHmbXtRSNTHyJ58BPjBzKYu0m5nsE5g+C1AXTbWFdhOj43KzJpUwDZPqbYf/LiFI9qlr7XjiBVv4P/A/6wKuMrCVgEq3ApQULutwHI7E2yKc5jcDsunlikSe11XEyO36H6WdmZyhCYRKu0jhN79fmQxZGrypOFDIw2IIEw==
    MB_ENCRYPTION_SECRET_KEY: AgCTPgOzPo+WifYELzAwAY31riRGrqoziMUlBSe5r15FPFt1Jh036ia4+ylZXlCwYnwsPOFWftuPFdZW107O/FG9/DkLnT6VuI+R9AHLKrugTtE3DVQftI1YMSR1phVslbaAnRvfX3GRUhf1EFGXRhTupo/hpOTPGIC2dkNxCuPL6QWpi0tzqS1K74ANomNFhTAS5fcr8t7E0wajpwN+1mKOoKxoAHovL3ARjHSypLSrJd8xEkept4RbuQt0JTaWWnEOW5UNUkgWIJHXo24Uea8eiZXkMZ2tVyo8CDyznNiL+bqdODANiK/SKZ4fafP5qL9pibo5pZzEZW6C1xE+CHXzpoej3+G7KZdi0e5yk8+QbqTncHT1DcjcLUdW7wXU45TbzWWU/1ikgcwrTtTRm0SgIqzyGoEexiPxtvtPq895ZCouRPxhm6kI2jgz9fboYTDY4Hdn5zSc/S/Vg3s9scirCkRIutVOycHsIxlgx9pGU2KbgKpteXaCn9i8FT84/raN1ZKXNt7xz5t6ZEDNRwa5XtX1WoLn+Od5Mujoe589Xlve05nusdqfcmCElqe5RJ5PRQ0F+MYIZtdV547k4VENcPS8ZnxFLaDvaTCOtbS529GPHW/mpOATOjv6vW3OeIS3YxeRUjDUcAU71f5GL4xCWZnbIslSkcciLljVtpDrJR5ai+Mg/9SkaPPQ8aA78KvQnejIpvdw1RPKYnDIJZG0EgqGq+gzZsBPIzOxQ2U=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: metabase
    type: Opaque
