jobs:
  runs:
    build-backend:
      with:
        buildArgs:
          DOMIFA_BACKEND_URL: "https://domifa-api.{{ .Values.global.domain }}/"
          DOMIFA_PORTAIL_ADMINS_URL: "https://admin-{{ .Values.global.host }}/"
          DOMIFA_PORTAIL_USAGERS_URL: "https://mon-{{ .Values.global.host }}/"

    build-frontend:
      with:
        buildArgs:
          DOMIFA_BACKEND_URL: "https://domifa-api.{{ .Values.global.domain }}/"
          DOMIFA_FRONTEND_META_ROBOTS: index,follow

    build-portail-admins:
      with:
        buildArgs:
          DOMIFA_BACKEND_URL: "https://domifa-api.{{ .Values.global.domain }}/"
          PRODUCTION: "true"

    build-portail-usagers:
      with:
        buildArgs:
          DOMIFA_BACKEND_URL: "https://domifa-api.{{ .Values.global.domain }}/"
          PRODUCTION: "true"
          DOMIFA_FRONTEND_META_ROBOTS: index,follow

backend-cron:
  ~needs: [build-backend]
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits: # exports need a lot of CPU/RAM ATM
      cpu: 3
      memory: 3Gi
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
    - secretRef:
        name: domifa-encryption-key
  vars: &backendVars
    DOMIFA_ENV_ID: "prod"
    DOMIFA_BACKEND_URL: "https://domifa-api.{{ .Values.global.domain }}/"
    DOMIFA_FRONTEND_URL: "https://{{ .Values.global.host }}/"
    DOMIFA_PORTAIL_USAGERS_URL: "https://mon-{{ .Values.global.host }}/"
    DOMIFA_PORTAIL_ADMINS_URL: "https://admin-{{ .Values.global.host }}/"
  env: &backendEnv
    - name: S3_BUCKET_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: domifa-prod-app-access-key
          key: bucket_endpoint
    - name: S3_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: domifa-prod-app-access-key
          key: bucket_name
    - name: S3_BUCKET_REGION
      valueFrom:
        secretKeyRef:
          name: domifa-prod-app-access-key
          key: bucket_region
    - name: S3_BUCKET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: domifa-prod-app-access-key
          key: bucket_access_key
    - name: S3_BUCKET_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: domifa-prod-app-access-key
          key: bucket_secret_key
    - name: S3_BUCKET_ROOT_DIR
      value: backup/files

backend: &backendProd
  ~needs: [backend-cron]
  host: "domifa-api.{{ .Values.global.domain }}"
  autoscale:
    minReplicas: 3
    maxReplicas: 8
    enabled: true
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits: # exports need a lot of CPU/RAM ATM
      cpu: 3
      memory: 3Gi
  certSecretName: backend-crt
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
    - secretRef:
        name: domifa-encryption-key
  vars:
    <<: *backendVars
  env: *backendEnv

backend-export:
  <<: *backendProd
  ~needs: [backend-cron]
  ingress:
    paths:
      - /export
      - /admin/structures/export

frontend:
  replicas: 1
  host: "{{ .Values.global.host }}"
  certSecretName: frontend-crt

portail-admins:
  replicas: 1
  host: "admin-{{ .Values.global.host }}"
  certSecretName: portail-admins-crt

portail-usagers:
  replicas: 1
  host: "mon-{{ .Values.global.host }}"
  certSecretName: portail-usagers-crt
