export type ContactSupportSubject =
  | "INSCRIPTION_SUPPRESSION_STRUCTURE"
  | "FORMATION"
  | "PROPOSITION_EVOLUTION"
  | "STATISTIQUES_RAPPORT_ACTIVITE"
  | "QUESTION_JURIDIQUE_SECURITE"
  | "QUESTION_MON_DOMIFA"
  | "ASSISTANCE_TECHNIQUE"
  | "PROBLEME_ACCESSIBILITE"
  | "AUTRE";
