apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: {}
  name: azure-storage
  namespace: domifa
spec:
  encryptedData:
    azurestorageaccountname: >-
      AgCkDUoP6ioGLNaC/j2IuxdxZTFRa7KSyLSZkorXMSF3UHZBgEc5dF4pSttccCJSws5ZrYvT2/acUcNKM9qPIz+ESgU+CZYnLAuYjLm53YtDZUNV4/NfTgQYyNGY4dhWwb2NHV6b4snWh3kP/gkD9NuOYuC42XlRic4b4qeR+gmczhp28zGbp2Bi5qQa6K1rGk7/5+y+y5TFlXGC+A0Cm0IGS2zKHFbbgg2wb3J6stpfvbmf5VdGLjy+M2GlS066f5YxYLzuA9vWIjQ8/BKWKRW+zn4e4/klapurekUpToBWg1jKrkcDtaxcfXporTfGuW3M2c3fX0TVSPgDsTkKR4YV7iN4q8s+dHm/4QZqk1KlEnVukXiv5atn850r3tk4Cwu329VbZzfQUz9ncIgWnMV4b6rJifLVqsaxi8tmCPP8/5G8JNxiC46fkGv59NTT5SC39H5C4Pz/y92nU6n2AjMihB+Kolc2KRxaSt0ArXecMPrwoa0a3ZSi0ciiHEFpAi2+X/Pg3daBu3uf/WQ635uejdDh+ibcl75Q7rNRmkoKLtTJiCrMOT266LLuX+sJJR1i28JIPtmLvPaCLH3f+xxabQyOVM+heetJon1f6U0VT0EnlD1ykoBKv1VTnlgmm0lXsL/rqTivW/H3udAYMxy79JLHwjbaueamfIgeHLlYcWdXugyaNgT3LEb2Db+yCvip/Dk8CBJTWxE=
    azurestorageaccountkey: >-
      AgBw9nemSgrGiCzN5ktKKCL0beEfVLpB1VhGqFu30r03fpUaPXw+QpUVbYlRPU/DdlxjBM2DSxuLSvCk9u0rLptbTozhksklx2ELXVmI8+s/la/TX7aiUg2NvTA8UWvwQ9QyabuuEqPIUAtJJFqqdXyC4bVO8PbhZjqh6CnqjPl7haNBZfLo93B2PJmzs0R44EV0YJCCBlIJcyra2tbg+9WB1mtJ0en3JTlpC2ESl35nlj+EdKUgUeb5KqKAtPXVFRBzv2w/mOYJYSCVe7n99D3ZDW0vTsigNk+svZqjM4QM3oY+x+p0iAVAK6z6xsCHEsHgh8MfA9DaSQ1fxoLRauxXcPdmNsahqaNJPq+T1Oqcyt5UFPlxjBivetvE5WLDbgcO98Z5iEJCem26LheBtQg0IDfNqulq55NH6U8WOYlzUfCkY/Wfgby7MS2Gt/5QxGZeaUEDJkADZOpVVEHBATYVgUPzKxxtxEa4Y/7Q+SlWQC3hg0b+sMP7XxWoBn6LbeCNhUoqKxQbPLYoRBfMiaiX7mCeV6sThpvVfTqzGRbq9NXcHrnl4KDc6p4+5GsZXM3tiwM1Aj3dAzKm4JkkceWFTCogw5B2Kezjxa8FZtzhdlwUu5YGwCECc9KNQH9YxSxLDQ85RXsH1tSWW01YTrjWVhYLFZCpWQkZryXJs0hYGRelpXodIBA8y3tM6xT3hv0XtFXHWzVHNPeRugd0ORwGMAEB7ug6kIhSKSsYe1BagjxJpaG17Wv7HcR83E0AWnQVxagrhaOB9927x0AJEmlnRER6QjLV61/dgUm9oB9ORaTXFbo1KITB
  template:
    metadata:
      annotations: {}
      name: azure-storage
    type: Opaque
