export const STRUCTURE_NAMES = {
  "4AJ Plateforme Logement Jeunes CLLAJ ARRAS": "asso",
  "A fratellanza": "asso",
  "Abri de la Providence": "asso",
  "ACCEPTESS-T": "asso",
  ACCES: "asso",
  "Accueil de Jour Association Eole": "asso",
  "Accueil de jour de Douai Croix rouge Française": "asso",
  "AHLIS 46": "asso",
  "AIDE A L'INSERTION DES DEMANDEURS D'ASILE": "asso",
  AVAF: "asso",
  "BOUTIQUE SOLIDARITÉ EMMAÜS DE BEAUVAIS": "asso",
  "Boutique Solidarité": "asso",
  Bruillot: "asso",
  "C.C.A.S de la commune de Martillac": "ccas",
  "C.C.A.S DE PAMIERS": "ccas",
  "CIAS de Domène": "cias",
  Vista: "asso",
};
