name: "Signaler un bug"
description: "Problème à corriger / anomalie bloquante pour les utilisateurs"
title: "🐞 Bug - "
labels: ["bug"]
assignees: ["pYassine"]
projects: ["SocialGouv/81"]
body:
  - type: checkboxes
    id: sites
    attributes:
      label: "🖥️ Site(s) concerné(s)"
      options:
        - label: "DomiFa - côté structures"
          required: false
        - label: "Mon DomiFa - portail domiciliés"
          required: false
        - label: "Admin DomiFa"
          required: false
        - label: "Metabase"
          required: false

  - type: textarea
    id: description
    attributes:
      label: "🚫 Description du problème"
      description: "Précisez les étapes pour reproduire directement. \nVous pouvez glisser des captures d'écran directement dans ce champs. \n🧨 **IMPORTANT** : Veillez à masquer toute information personnelle ou confidentielle 🧨 "
      placeholder: "Ex: L'utilisateur n'arrive pas à charger les dossiers, le mail de renouvellement de mot de passe n'arrive jamais, etc"
    validations:
      required: true

  - type: input
    id: structure
    attributes:
      label: "Structure concernée (optionnel)"
      description: "ID uniquement, pas de donnée nominative"
      placeholder: "ex: 123"
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: "🔮 Comportement attendu"
      placeholder: "Décrivez ce qui devrait se passer normalement"
    validations:
      required: true
