apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: s3
  namespace: domifa-restore
spec:
  encryptedData:
    TOKEN: AgCbbXzeCN7+hq8tsncJq8M0VrZCR35n1aZSY0f+w45Oa9IHKYTB5E2xE8xlL7tppMRE7FF7Oqw/MmH6uFJJJ2iqF1h2GOCty/P0f5N+7NWnCQkenJnH8JY9GipPEd4RZ9+D06fBlVXT+IOAMred7BoN7bmnh90nOyh+qbeNF9+Szez5wWb4bA0HoFYblRIWiXQpOqpNuQncrKAUUd+eiL8fQCInMTtIDnemiOzceLJGNBwyCFBA3Y7gesgB0563GeK9l9HZzV9FDP/FLzxUG/n2Ir9Tz4q6UTDxU8CCI4VmEDpz3Chd5hSnWWFz/KlDLt302buL2NhBpfel9aSl8QJdF1io4hnww+IfbCZpW/U9bCdbP01MwVON7oByo+Ce5oiGKAYlm1r2pXFXyMJzjCJT5JSwl9Ld2dIuqU3pNePM6gTF/Yca+Z62NShzctqW+lbLEkLi/pGksVArR3nwHIBME22F+SxkYIfe5jUVfddnDN5C8BZWq8rCAd/M0vrNNb+iclTDGSeh3wfDH/f0hm5+xGID1XmMU/qaPFZYObPV8xX2BW6HYgY386Zq3ltzinM4ogI0xachw4+1Vp+N0HyLnfACoJ4YWjP9PCVka9fdX4fRdVX4IVsnnuMemwuAs8+815OoUdj3DBk1oLLJML+Eq/83ilRN50fUkN0cObc6AVix9BXHqBsAXwl7on9+lQ29qefY
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: s3
    type: Opaque
