// constante dupliquée côté frontend

import { type RegionDef } from "../interfaces/RegionDef.interface";

// https://fr.wikipedia.org/wiki/Liste_des_d%C3%A9partements_fran%C3%A7ais
export const REGIONS_DEF: RegionDef[] = [
  {
    regionCode: "01",
    regionName: "Guadeloupe",
    regionId: "guadeloupe",
    timeZone: "America/Guadeloupe",
    departements: [{ departmentCode: "971", departmentName: "Guadeloupe" }],
  },
  {
    regionCode: "02",
    regionName: "Martinique",
    regionId: "martinique",
    timeZone: "America/Martinique",
    departements: [{ departmentCode: "972", departmentName: "Martinique" }],
  },
  {
    regionCode: "03",
    regionName: "Guyane",
    regionId: "guyane",
    timeZone: "America/Cayenne",
    departements: [{ departmentCode: "973", departmentName: "Guyane" }],
  },
  {
    regionCode: "04",
    regionName: "La Réunion",
    regionId: "la-reunion",
    timeZone: "Indian/Reunion",
    departements: [{ departmentCode: "974", departmentName: "La Réunion" }],
  },
  {
    regionCode: "06",
    regionName: "Mayotte",
    regionId: "mayotte",
    timeZone: "Indian/Mayotte",
    departements: [{ departmentCode: "976", departmentName: "Mayotte" }],
  },
  {
    regionCode: "11",
    regionName: "Île-de-France",
    timeZone: "Europe/Paris",
    regionId: "ile-de-france",
    departements: [
      { departmentCode: "75", departmentName: "Paris" },
      { departmentCode: "77", departmentName: "Seine-et-Marne" },
      { departmentCode: "78", departmentName: "Yvelines" },
      { departmentCode: "91", departmentName: "Essonne" },
      { departmentCode: "92", departmentName: "Hauts-de-Seine" },
      { departmentCode: "93", departmentName: "Seine-Saint-Denis" },
      { departmentCode: "94", departmentName: "Val-de-Marne" },
      { departmentCode: "95", departmentName: "Val-d'oise" },
    ],
  },
  {
    regionCode: "24",
    regionName: "Centre-Val de Loire",
    timeZone: "Europe/Paris",
    regionId: "centre-val-de-loire",
    departements: [
      { departmentCode: "18", departmentName: "Cher" },
      { departmentCode: "28", departmentName: "Eure-et-Loir" },
      { departmentCode: "36", departmentName: "Indre" },
      { departmentCode: "37", departmentName: "Indre-et-Loire" },
      { departmentCode: "41", departmentName: "Loir-et-Cher" },
      { departmentCode: "45", departmentName: "Loiret" },
    ],
  },
  {
    regionCode: "27",
    regionName: "Bourgogne-Franche-Comté",
    timeZone: "Europe/Paris",
    regionId: "bourgogne-franche-comte",
    departements: [
      { departmentCode: "21", departmentName: "Côte-d'Or" },
      { departmentCode: "25", departmentName: "Doubs" },
      { departmentCode: "39", departmentName: "Jura" },
      { departmentCode: "58", departmentName: "Nièvre" },
      { departmentCode: "70", departmentName: "Haute-Saône" },
      { departmentCode: "71", departmentName: "Saône-et-Loire" },
      { departmentCode: "89", departmentName: "Yonne" },
      { departmentCode: "90", departmentName: "Territoire de Belfort" },
    ],
  },
  {
    regionCode: "28",
    regionName: "Normandie",
    timeZone: "Europe/Paris",
    regionId: "normandie",
    departements: [
      { departmentCode: "14", departmentName: "Calvados" },
      { departmentCode: "27", departmentName: "Eure" },
      { departmentCode: "50", departmentName: "Manche" },
      { departmentCode: "61", departmentName: "Orne" },
      { departmentCode: "76", departmentName: "Seine-Maritime" },
    ],
  },
  {
    regionCode: "32",
    regionName: "Hauts-de-France",
    timeZone: "Europe/Paris",
    regionId: "hauts-de-france",
    departements: [
      { departmentCode: "02", departmentName: "Aisne" },
      { departmentCode: "59", departmentName: "Nord" },
      { departmentCode: "60", departmentName: "Oise" },
      { departmentCode: "62", departmentName: "Pas-de-Calais" },
      { departmentCode: "80", departmentName: "Somme" },
    ],
  },
  {
    regionCode: "44",
    regionName: "Grand Est",
    regionId: "grand-est",
    timeZone: "Europe/Paris",
    departements: [
      { departmentCode: "08", departmentName: "Ardennes" },
      { departmentCode: "10", departmentName: "Aube" },
      { departmentCode: "51", departmentName: "Marne" },
      { departmentCode: "52", departmentName: "Haute-Marne" },
      { departmentCode: "54", departmentName: "Meurthe-et-Moselle" },
      { departmentCode: "55", departmentName: "Meuse" },
      { departmentCode: "57", departmentName: "Moselle" },
      { departmentCode: "67", departmentName: "Bas-Rhin" },
      { departmentCode: "68", departmentName: "Haut-Rhin" },
      { departmentCode: "88", departmentName: "Vosges" },
    ],
  },
  {
    regionCode: "52",
    regionName: "Pays de la Loire",
    regionId: "pays-de-la-loire",
    timeZone: "Europe/Paris",
    departements: [
      { departmentCode: "44", departmentName: "Loire-Atlantique" },
      { departmentCode: "49", departmentName: "Maine-et-Loire" },
      { departmentCode: "53", departmentName: "Mayenne" },
      { departmentCode: "72", departmentName: "Sarthe" },
      { departmentCode: "85", departmentName: "Vendée" },
    ],
  },
  {
    regionCode: "53",
    regionName: "Bretagne",
    regionId: "bretagne",
    timeZone: "Europe/Paris",
    departements: [
      { departmentCode: "22", departmentName: "Côtes-d'armor" },
      { departmentCode: "29", departmentName: "Finistère" },
      { departmentCode: "35", departmentName: "Ille-et-Vilaine" },
      { departmentCode: "56", departmentName: "Morbihan" },
    ],
  },
  {
    regionCode: "75",
    regionName: "Nouvelle-Aquitaine",
    regionId: "nouvelle-aquitaine",
    timeZone: "Europe/Paris",
    departements: [
      { departmentCode: "16", departmentName: "Charente" },
      { departmentCode: "17", departmentName: "Charente-Maritime" },
      { departmentCode: "19", departmentName: "Corrèze" },
      { departmentCode: "23", departmentName: "Creuse" },
      { departmentCode: "24", departmentName: "Dordogne" },
      { departmentCode: "33", departmentName: "Gironde" },
      { departmentCode: "40", departmentName: "Landes" },
      { departmentCode: "47", departmentName: "Lot-et-Garonne" },
      { departmentCode: "64", departmentName: "Pyrénées-Atlantiques" },
      { departmentCode: "79", departmentName: "Deux-Sèvres" },
      { departmentCode: "86", departmentName: "Vienne" },
      { departmentCode: "87", departmentName: "Haute-Vienne" },
    ],
  },
  {
    regionCode: "76",
    regionName: "Occitanie",
    regionId: "occitanie",
    timeZone: "Europe/Paris",
    departements: [
      { departmentCode: "09", departmentName: "Ariège" },
      { departmentCode: "11", departmentName: "Aude" },
      { departmentCode: "12", departmentName: "Aveyron" },
      { departmentCode: "30", departmentName: "Gard" },
      { departmentCode: "31", departmentName: "Haute-Garonne" },
      { departmentCode: "32", departmentName: "Gers" },
      { departmentCode: "34", departmentName: "Hérault" },
      { departmentCode: "46", departmentName: "Lot" },
      { departmentCode: "48", departmentName: "Lozère" },
      { departmentCode: "65", departmentName: "Hautes-Pyrénées" },
      { departmentCode: "66", departmentName: "Pyrénées-Orientales" },
      { departmentCode: "81", departmentName: "Tarn" },
      { departmentCode: "82", departmentName: "Tarn-et-Garonne" },
    ],
  },
  {
    regionCode: "84",
    regionName: "Auvergne-Rhône-Alpes",
    regionId: "auvergne-rhone-alpes",
    timeZone: "Europe/Paris",
    departements: [
      { departmentCode: "01", departmentName: "Ain" },
      { departmentCode: "03", departmentName: "Allier" },
      { departmentCode: "07", departmentName: "Ardèche" },
      { departmentCode: "15", departmentName: "Cantal" },
      { departmentCode: "26", departmentName: "Drôme" },
      { departmentCode: "38", departmentName: "Isère" },
      { departmentCode: "42", departmentName: "Loire" },
      { departmentCode: "43", departmentName: "Haute-Loire" },
      { departmentCode: "63", departmentName: "Puy-de-Dôme" },
      { departmentCode: "69", departmentName: "Rhône" },
      { departmentCode: "73", departmentName: "Savoie" },
      { departmentCode: "74", departmentName: "Haute-Savoie" },
    ],
  },
  {
    regionCode: "93",
    regionName: "Provence-Alpes-Côte d'Azur",
    regionId: "paca",
    timeZone: "Europe/Paris",
    departements: [
      { departmentCode: "04", departmentName: "Alpes-de-Haute-Provence" },
      { departmentCode: "05", departmentName: "Hautes-Alpes" },
      { departmentCode: "06", departmentName: "Alpes-Maritimes" },
      { departmentCode: "13", departmentName: "Bouches-du-Rhône" },
      { departmentCode: "83", departmentName: "Var" },
      { departmentCode: "84", departmentName: "Vaucluse" },
    ],
  },
  {
    regionCode: "94",
    regionId: "corse",
    regionName: "Corse",
    timeZone: "Europe/Paris",
    departements: [
      { departmentCode: "2A", departmentName: "Corse-du-Sud" },
      { departmentCode: "2B", departmentName: "Haute-Corse" },
    ],
  },
  {
    regionCode: "NC",
    regionId: "nouvelle-caledonie",
    regionName: "Nouvelle Calédonie",
    timeZone: "Pacific/Noumea",
    departements: [
      { departmentCode: "988", departmentName: "Nouvelle Calédonie" },
    ],
  },
  {
    regionCode: "PO",
    regionId: "polynesie-française",
    regionName: "Polynésie Française",
    timeZone: "Pacific/Tahiti",
    departements: [
      { departmentCode: "987", departmentName: "Polynésie Française" },
    ],
  },
  {
    regionCode: "SB",
    regionId: "saint-barthelemy",
    timeZone: "America/Martinique",
    regionName: "Saint-Barthélemy",
    departements: [
      { departmentCode: "977", departmentName: "Saint-Barthélemy" },
    ],
  },
  {
    regionCode: "SM",
    regionId: "saint-martin",
    regionName: "Saint-Martin",
    timeZone: "America/Martinique",
    departements: [{ departmentCode: "978", departmentName: "Saint-Martin" }],
  },
  {
    regionCode: "SP",
    regionId: "saint-pierre-et-miquelon",
    regionName: "Saint-Pierre-et-Miquelon",
    timeZone: "America/Miquelon",
    departements: [
      { departmentCode: "975", departmentName: "Saint-Pierre-et-Miquelon" },
    ],
  },
  {
    regionCode: "WF",
    regionId: "wallis-et-futuna",
    regionName: "Wallis-et-Futuna",
    timeZone: "Pacific/Wallis",
    departements: [
      { departmentCode: "986", departmentName: "Wallis-et-Futuna" },
    ],
  },
  {
    regionCode: "TF",
    regionId: "terres-australes-francaises",
    regionName: "Terres australes françaises",
    timeZone: "Indian/Maldives",
    departements: [
      {
        departmentCode: "984",
        departmentName: "Terres australes françaises",
      },
    ],
  },
];
