

.deploy_stage: &deploy_stage
  stage: "Deploy"
  dependencies: []
  services:
    - docker:$DOCKER_VERSION-dind
  variables: &deploy_stage_variables
    IMAGE_TAG: master
    REGISTRY: $CI_REGISTRY_IMAGE

.dev_stage: &dev_stage
  environment:
    name: fabrique-dev
  only:
    refs:
      - branches
      - tags
  except:
    variables:
      - $PRODUCTION


Create namespace:
  <<: *deploy_stage
  <<: *dev_stage
  extends: .base_docker_kube_image_stage
  stage: "Registration"
  script:
    # Skip the job if the namespace exists
    - "[[ $(kubectl get namespace ${K8S_NAMESPACE}) ]] && exit ${CI_JOB_SKIP_EXIT_CODE:-0}"
    # Or (re)create to ensure new quota are applied
    # - kubectl delete namespaces ${K8S_NAMESPACE} || true
    #
    - kubectl create namespace ${K8S_NAMESPACE}
    - kubectl annotate namespace ${K8S_NAMESPACE} field.cattle.io/projectId=${RANCHER_PROJECT_ID}
    - kubectl annotate namespace ${K8S_NAMESPACE} git/branch=${CI_COMMIT_REF_NAME}


Deploy backend:
  <<: *deploy_stage
  <<: *dev_stage
  extends: .base_docker_helm_image_stage
  script:
    - envsubst < ./.k8s/backend/values.yaml > ./values.yaml
    - cat ./values.yaml
    #
    - helm init --client-only
    - helm repo add socialgouv https://github.com/SocialGouv/helm-charts/releases/download/${HELM_CHART_VERSION}
    - helm upgrade
        ${K8S_PROJECT}-backend-${BRANCH_HASH}
        socialgouv/webapp
        --install
        --namespace ${K8S_NAMESPACE}
        --values ./values.yaml
        --wait || helm delete --purge ${K8S_PROJECT}-backend-${BRANCH_HASH}

Deploy MongoDB:
  <<: *deploy_stage
  <<: *dev_stage
  extends: .base_docker_helm_image_stage
  script:
    - envsubst < ./.k8s/mongodb/values.yaml > ./values.yaml
    - cat ./values.yaml
    #
    - helm init --client-only
    - helm upgrade
        ${MONGODB_HOST}
        stable/mongodb
        --install
        --namespace ${K8S_NAMESPACE}
        --values ./values.yaml
        --wait || helm delete --purge ${MONGODB_HOST}

