export const FIRST_SHEET_USAGERS = [
  {
    AD_DATE_NAISSANCE_0: "Date naissance ayant-droit 1",
    AD_DATE_NAISSANCE_1: "Date naissance ayant-droit 2",
    AD_DATE_NAISSANCE_2: "Date naissance ayant-droit 3",
    AD_DATE_NAISSANCE_3: "Date naissance ayant-droit 4",
    AD_DATE_NAISSANCE_4: "Date naissance ayant-droit 5",
    AD_DATE_NAISSANCE_5: "Date naissance ayant-droit 6",
    AD_DATE_NAISSANCE_6: "Date naissance ayant-droit 7",
    AD_DATE_NAISSANCE_7: "Date naissance ayant-droit 8",
    AD_LIEN_0: "Lien de parenté 1",
    AD_LIEN_1: "Lien de parenté 2",
    AD_LIEN_2: "Lien de parenté 3",
    AD_LIEN_3: "Lien de parenté 4",
    AD_LIEN_4: "Lien de parenté 5",
    AD_LIEN_5: "Lien de parenté 6",
    AD_LIEN_6: "Lien de parenté 7",
    AD_LIEN_7: "Lien de parenté 8",
    AD_NOM_0: "Nom ayant-droit 1",
    AD_NOM_1: "Nom ayant-droit 2",
    AD_NOM_2: "Nom ayant-droit 3",
    AD_NOM_3: "Nom ayant-droit 4",
    AD_NOM_4: "Nom ayant-droit 5",
    AD_NOM_5: "Nom ayant-droit 6",
    AD_NOM_6: "Nom ayant-droit 7",
    AD_NOM_7: "Nom ayant-droit 8",
    AD_PRENOM_0: "Prénom ayant-droit 1",
    AD_PRENOM_1: "Prénom ayant-droit 2",
    AD_PRENOM_2: "Prénom ayant-droit 3",
    AD_PRENOM_3: "Prénom ayant-droit 4",
    AD_PRENOM_4: "Prénom ayant-droit 5",
    AD_PRENOM_5: "Prénom ayant-droit 6",
    AD_PRENOM_6: "Prénom ayant-droit 7",
    AD_PRENOM_7: "Prénom ayant-droit 8",
    AYANTS_DROITS_NOMBRE: "Nombre d'ayants-droit",
    DATE_DEBUT_DOM: "Date de Début de la domiciliation (ex: 12/10/2020)",
    DATE_DERNIER_PASSAGE: "Date de dernier passage (ex: 01/09/2020 à 10h45)",
    DATE_FIN_DOM: "Date de fin de la domiciliation (ex: 12/10/2020)",
    DATE_PREMIERE_DOM: "Date de la 1ere domiciliation (ex: 12/10/2020)",
    DATE_RADIATION: "Date de la radiation",
    DATE_REFUS: "Date du refus",
    DECISION_NOM_AGENT: "Utilisateur ayant prit la décision",
    MOTIF_RADIATION: "Motif de la radiation",
    MOTIF_REFUS: "Motif du refus",
    STATUT_DOM: "Statut de la domiciliation",
    TYPE_DOM: "Type de domiciliation",
    USAGER_CIVILITE: "Civilité",
    PREMIERE_DOM_NOM_AGENT: "Utilisateur ayant validé la 1ere dom",
    USAGER_DATE_NAISSANCE: "Date naissance",
    USAGER_EMAIL: "Adresse email",
    USAGER_LANGUE: "Langue parlée",
    USAGER_LIEU_NAISSANCE: "Lieu naissance",
    USAGER_NATIONALITE: "Nationalité",
    USAGER_CUSTOM_REF: "Identifiant personnalisé",
    USAGER_NUMERO_DISTRIBUTION_SPECIALE:
      "Numéro de distribution (TSA, BP, etc)",
    USAGER_PHONE: "Numéro de téléphone",
    USAGER_PRENOM: "Prénom",
    USAGER_NOM: "Nom",
    USAGER_SURNOM: "Nom d'usage / Surnom",
  },
  {
    AYANTS_DROITS_NOMBRE: "0",
    DATE_DEBUT_DOM: "01/11/2020",
    DATE_DERNIER_PASSAGE: "01/11/2020",
    DATE_FIN_DOM: "31/10/2021",
    DATE_PREMIERE_DOM: "01/10/2018",
    DATE_RADIATION: "",
    DATE_REFUS: "",
    DECISION_NOM_AGENT: "Patrick Roméro",
    MOTIF_RADIATION: "",
    MOTIF_REFUS: "",
    PREMIERE_DOM_NOM_AGENT: "",
    STATUT_DOM: "Actif",
    TYPE_DOM: "Première domiciliation",
    USAGER_CIVILITE: "Monsieur",
    USAGER_DATE_NAISSANCE: "02/11/1988",
    USAGER_EMAIL: "fake-mail@yopmail.com",
    USAGER_LANGUE: "",
    USAGER_LIEU_NAISSANCE: "Paris",
    USAGER_NATIONALITE: "",
    USAGER_NOM: "NOUVEAU",
    USAGER_NUMERO_DISTRIBUTION_SPECIALE: "",
    USAGER_PHONE: "+33 6 06 06 06 06",
    USAGER_PRENOM: "DOSSIER",
    USAGER_CUSTOM_REF: "6",
    USAGER_SURNOM: "TEST",
  },
  {
    AD_DATE_NAISSANCE_0: "20/12/1978",
    AD_LIEN_0: "CONJOINT",
    AD_NOM_0: "Karamoko",
    AD_PRENOM_0: "Mauricette",
    AYANTS_DROITS_NOMBRE: "1",
    DATE_DEBUT_DOM: "",
    DATE_DERNIER_PASSAGE: "01/12/2020",
    DATE_FIN_DOM: "",
    DATE_PREMIERE_DOM: "11/01/2018",
    DATE_RADIATION: "",
    DATE_REFUS: "12/02/2020",
    DECISION_NOM_AGENT: "Testeur Robin",
    MOTIF_RADIATION: "",
    MOTIF_REFUS: "Absence de lien avec la commune",
    PREMIERE_DOM_NOM_AGENT: "",
    STATUT_DOM: "Refusé",
    TYPE_DOM: "Renouvellement",
    USAGER_CIVILITE: "Madame",
    USAGER_DATE_NAISSANCE: "07/08/1998",
    USAGER_EMAIL: "domicilie2@yopmail.com",
    USAGER_LANGUE: "",
    USAGER_LIEU_NAISSANCE: "Bouaké, Côte d'Ivoire",
    USAGER_NATIONALITE: "",
    USAGER_NOM: "Martine",
    USAGER_NUMERO_DISTRIBUTION_SPECIALE: "",
    USAGER_PHONE: "+33 6 06 06 06 06",
    USAGER_PRENOM: "Sembat",
    USAGER_CUSTOM_REF: "5",
    USAGER_SURNOM: "",
  },
];
