export type UsagerEntretienTypeMenage =
  | "COUPLE_AVEC_ENFANT"
  | "COUPLE_SANS_ENFANT"
  | "FEMME_ISOLE_AVEC_ENFANT"
  | "FEMME_ISOLE_SANS_ENFANT"
  | "HOMME_ISOLE_AVEC_ENFANT"
  | "HOMME_ISOLE_SANS_ENFANT";
