global:
  pgSecretName: pg-app

pg-metabase:
  ~chart: pg

backend:
  host: "api-{{ .Values.global.host }}"
  addVolumes:
    - files
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
    - secretRef:
        name: azure-domifa-volume
    - secretRef:
        name: domifa-encryption-key

backend-cron:
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap

frontend:
  host: "{{ .Values.global.host }}"

portail-admins:
  host: "admin-{{ .Values.global.host }}"

portail-usagers:
  host: "mon-{{ .Values.global.host }}"

metabase:
  enabled: true
  ingress:
    enabled: false
  envFrom:
    - secretRef:
        name: pg-metabase-app

oauth2-proxy:
  enabled: true
  host: "metabase-domifa-preprod.dev.fabrique.social.gouv.fr"
  additionalArgs:
    - --skip-auth-route
    - ^/public/.*,^/app/dist/.*,^/api/public/.*,^/api/session/.*,^/app/assets/.*,^/api/geojson/.*
  upstream: http://metabase
  envFrom:
    - secretRef:
        name: oauth2-proxy
    - configMapRef:
        name: oauth2-proxy
