global:
  pgSecretName: pg-app

pg:
  cnpg-cluster:
    persistence:
      size: "30Gi"
    resources:
      requests:
        memory: 3Gi
      limits:
        memory: 3Gi

pg-metabase:
  ~chart: pg

backend:
  host: "api-{{ .Values.global.host }}"
  ~needs: [build-backend, pg]
  addVolumes:
    - files
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
    - secretRef:
        name: azure-domifa-volume
    - secretRef:
        name: domifa-encryption-key

backend-cron:
  ~needs: [backend]
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap

frontend:
  host: "{{ .Values.global.host }}"

portail-admins:
  host: "admin-{{ .Values.global.host }}"

portail-usagers:
  host: "mon-{{ .Values.global.host }}"

metabase:
  enabled: true
  ~chart: metabase
  ~needs: [pg-metabase]
  ingress:
    enabled: false
  envFrom:
    - secretRef:
        name: pg-metabase-app
    - secretRef:
        name: metabase
  env:
    - name: MB_DB_CONNECTION_URI
      value: "$(DATABASE_URL)"

oauth2-proxy:
  enabled: true
  host: "metabase-domifa-preprod.dev.fabrique.social.gouv.fr"
  additionalArgs:
    - --skip-auth-route
    - ^/public/.*,^/app/dist/.*,^/api/public/.*,^/api/session/.*,^/app/assets/.*,^/api/geojson/.*
  upstream: http://metabase
  envFrom:
    - secretRef:
        name: oauth2-proxy
    - configMapRef:
        name: oauth2-proxy
