backend: &backendPreprod
  host: "api-{{ .Values.global.host }}"
  ~needs: [build-backend, pg]
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
    - secretRef:
        name: domifa-encryption-key
  env: &backendEnv
    - name: S3_BUCKET_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_endpoint
    - name: S3_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_name
    - name: S3_BUCKET_REGION
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_region
    - name: S3_BUCKET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_access_key
    - name: S3_BUCKET_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: domifa-dev-app-access-key
          key: bucket_secret_key
    - name: S3_BUCKET_ROOT_DIR
      value: preprod/files

backend-export:
  <<: *backendPreprod
  ~needs: [build-backend, pg]
  ingress:
    paths:
      - /export
      - /admin/structures/export

backend-cron:
  ~needs: [build-backend, pg]
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
  env: *backendEnv

frontend:
  host: "{{ .Values.global.host }}"

portail-admins:
  host: "admin-{{ .Values.global.host }}"

portail-usagers:
  host: "mon-{{ .Values.global.host }}"
