global:
  pgSecretName: pg-app

pg:
  ~chart: pg
  backup:
    name: ovh # backup on a new folder
  cnpg-cluster:
    persistence:
      size: "30Gi"
    resources:
      requests:
        memory: 3Gi
      limits:
        memory: 3Gi

backend:
  host: "api-{{ .Values.global.host }}"
  ~needs: [build-backend, pg]
  addVolumes:
    - files
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
    - secretRef:
        name: azure-domifa-volume
    - secretRef:
        name: domifa-encryption-key

backend-cron:
  ~needs: [backend]
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap

frontend:
  host: "{{ .Values.global.host }}"

portail-admins:
  host: "admin-{{ .Values.global.host }}"

portail-usagers:
  host: "mon-{{ .Values.global.host }}"
