global:
  pgSecretName: pg-app

pg:
  ~chart: pg
  backup:
    name: ovh-preprod # backup on a new folder
  cnpg-cluster:
    persistence:
      size: "30Gi"
    resources:
      requests:
        memory: 3Gi
      limits:
        memory: 3Gi
    recovery:
      enabled: true
      ~tpl~database: "{{ .Values.global.pgDatabase }}"
      ~tpl~owner: "{{ .Values.global.pgUser }}"
      secretName: "pg-db"
      barmanObjectStore:
        ~tpl~destinationPath: "s3://domifa-dev-backups/domifa-prod"
        s3Credentials:
          accessKeyId:
            ~tpl~name: "domifa-prod-backups-access-key"
            key: bucket_access_key
          secretAccessKey:
            ~tpl~name: "domifa-prod-backups-access-key"
            key: bucket_secret_key
          region:
            ~tpl~name: "domifa-prod-backups-access-key"
            key: bucket_region

backend:
  host: "api-{{ .Values.global.host }}"
  ~needs: [build-backend, pg]
  addVolumes:
    - files
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
    - secretRef:
        name: azure-domifa-volume
    - secretRef:
        name: domifa-encryption-key

backend-cron:
  ~needs: [backend]
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap

frontend:
  host: "{{ .Values.global.host }}"

portail-admins:
  host: "admin-{{ .Values.global.host }}"

portail-usagers:
  host: "mon-{{ .Values.global.host }}"
