export const IMPORT_PREVIEW_COLUMNS = {
  CUSTOM_ID: 0,
  CIVILITE: 1,
  NOM: 2,
  PRENOM: 3,
  SURNOM: 4,
  DATE_NAISSANCE: 5,
  LIEU_NAISSANCE: 6,
  PHONE: 7,
  EMAIL: 8,
  STATUT_DOM: 9,
  MOTIF_REFUS: 10,
  MOTIF_RADIATION: 11,
  TYPE_DOM: 12,
  DATE_DEBUT_DOM: 13,
  DATE_FIN_DOM: 14,
  DATE_PREMIERE_DOM: 15,
  DATE_DERNIER_PASSAGE: 16,

  ORIENTATION: 17,
  ORIENTATION_DETAILS: 18,
  DOMICILIATION_EXISTANTE: 19,
  REVENUS: 20,
  REVENUS_DETAILS: 21,
  LIEN_COMMUNE: 22,

  COMPOSITION_MENAGE: 23,
  SITUATION_RESIDENTIELLE: 24,
  SITUATION_DETAILS: 25,

  CAUSE_INSTABILITE: 26,
  CAUSE_DETAILS: 27,

  RAISON_DEMANDE: 28,
  RAISON_DEMANDE_DETAILS: 29,

  ACCOMPAGNEMENT: 30,
  ACCOMPAGNEMENT_DETAILS: 31,
  COMMENTAIRES: 32,

  AYANT_DROIT: [33, 37, 41, 45, 49, 53, 57, 61, 65],
};
