export const STREET_ABREVIATIONS = {
  av: "avenue",
  bd: "boulevard",
  ch: "chemin",
  imp: "impasse",
  pl: "place",
  r: "rue",
  all: "allée",
  rt: "route",
  sq: "square",
  fbg: "faubourg",
  qai: "quai",
  pass: "passage",
  chée: "chaussée",
  crs: "cours",
  prom: "promenade",
  sent: "sentier",
  v: "voie",
  rle: "ruelle",
};
