import { normalizeString } from "../../../search";
import { UserFonctionMapping } from "../interfaces";

export const USER_FONCTIONS: UserFonctionMapping[] = [
  {
    canonicalName: "Président",
    synonyms: [
      "président",
      "presidente",
      "présidente",
      "president",
      "presidente",
      "presidence",
      "président ccas",
      "président du ccas",
      "président du c.c.a.s.",
      "président du ccas et maire de la commune",
      "maire, président du ccas",
    ],
  },
  {
    canonicalName: "Directeur / Responsable",
    synonyms: [
      "directeur",
      "directrice",
      "directeur ",
      "directrice ",
      "diretrice",
      "directeur du ccas",
      "directrice du ccas",
      "directeur des services",
      "directrice des services",
      "directrice des services adultes en difficultés",
      "directrice locale de l'action sociale",
      "responsable",
      "respensable",
      "responsable du ccas",
      "responsable ccas",
      "responsable ccas de guipry-messac",
      "responsable action sociale",
      "responsable administrative",
      "responsable admissions",
      "responsable d'action sociale et logement",
      "responsable de la direction animation intergénérationnelle",
      "responsable de la paal",
      "responsable de l'epicerie solidaire",
      "responsable des affaires sociales",
      "responsable des aides légales et extra-légales",
      "responsable de service",
      "responsable du pôle de développement social",
      "responsable du pôle précarité",
      "responsable du pôle social",
      "responsable du service action sociale du ccas",
      "responsable pole action sociale",
      "responsable pôle social",
      "responsable pole social animations",
      "responsable service administration générale",
      "responsable service logement",
    ],
  },
  {
    canonicalName: "Directeur général des services (DGS)",
    synonyms: [
      "dgs",
      "directrice generale des services",
      "directeur général des services",
    ],
  },
  {
    canonicalName: "Maire",
    synonyms: ["maire", "maire de montélier", "ajoint au maire ccas"],
  },
  {
    canonicalName: "Chef de service",
    synonyms: [
      "chef de service",
      "cheffe de service",
      "chef de service logement spécifique",
    ],
  },
  {
    canonicalName: "Adjoint administratif",
    synonyms: [
      "adjoint administratif",
      "adjoint administratif 2ème classe",
      "adjoint administratif principal",
      "adjoint administratif service ccas",
      "adjoint administrative",
      "adjointe administrative",
      "adjointe  administrative",
      "adjoint au directeur",
      "adjointe aux affaires sociales - vice-présidente du ccas",
    ],
  },
  {
    canonicalName: "Secrétaire / Assistant administratif",
    synonyms: [
      "secrétaire",
      "secretaire",
      "secrétaire de mairie",
      "secrétaire de mairie",
      "secretaire de mairie",
      "secrétaire du ccas",
      "secrétaire ccas",
      "secrétaire accueil",
      "secrétaire en charge des affaires sociales",
      "secrétaire générale",
      "secrétaire mairie",
      "secrétaire ul",
      "secrétariat service social",
      "assistante",
      "assistante administrative",
      "assistante administrative ",
      "assistante administrative ccas logements",
      "assistante ccas",
      "assistante de direction",
      "assistante direction",
      "agent administratif",
      "agent adminstraitf en charge du ccas",
      "cadre administratif",
    ],
  },
  {
    canonicalName: "Travailleur social / Assistant social",
    synonyms: [
      "travailleur social",
      "travailleuse sociale",
      "assistant social rr",
      "assistante sociale",
      "assistante de service social",
      "assistante de service social lhss babinski",
      "assistant de service social",
      "conseillère sociale",
      "conseillere sociale - chu romain rolland",
      "educatrice",
    ],
  },
  {
    canonicalName: "Agent d'accueil",
    synonyms: [
      "agent d'accueil",
      "agent d'accueil administratif",
      "agent d'accueil social",
      "agent de premier accueil social",
      "accueillant",
      "chargé d'accueil social",
      "agen",
      "agent ",
      "agent du ccas",
      "agent ccas",
      "agent en charge du ccas",
      "agent social",
      "agent social ",
    ],
  },
  {
    canonicalName: "Chargé de mission action sociale",
    synonyms: [
      "charge de mission action sociale",
      "chargé de mission action sociale",
      "coordinateur pôle social ccas moulins",
      "coordinatrice d'appui aux interventions sociales",
      "coordinatrice de l'accueil social universel",
      "coordinatrice de la politique sociale",
      "coordinatrice medico sociale",
      "coordonnateur",
      "référente",
      "référente d'équipe",
      "référente pôle action sociale",
      "référente sociale",
      "gestionnaire sociale",
    ],
  },
  {
    canonicalName: "Conseiller en économie sociale et familiale (CESF)",
    synonyms: [
      "cesf",
      "conseillère esf",
      "conseiller economie sociale et familiale",
      "conseillère municipale",
      "conseillère municipale déléguée au social",
    ],
  },
  {
    canonicalName: "Personne en charge de la médiation sociale",
    synonyms: [
      "mediation sociale",
      "personne en charge de la médiation sociale",
      "animateur socio éducatif",
    ],
  },
  {
    canonicalName: "Personne en charge du RSA / Insertion",
    synonyms: ["rsa insertion", "personne en charge du rsa / insertion"],
  },
  {
    canonicalName: "Personne en charge de la domiciliation",
    synonyms: [
      "domiciliation",
      "chargée de domiciliation",
      "agent chargé des élections de domicile",
      "er accueil en charge des domiciliations",
    ],
  },
  {
    canonicalName: "Bénévole",
    synonyms: ["bénévole", "benevole", "bénévole domiciliation", "equipière"],
  },
  {
    canonicalName: "Autre",
    synonyms: [
      "autre",
      "vice-président",
      "vice président du ca du ccas",
      "vice président du c.c.a.s",
      "vice presidente",
      "vice-présidente",
      "vice présidente",
      "elue en charge du social",
      "cadre de santé",
      "ccas",
      "test",
      "null",
    ],
  },
];

export const NORMALIZED_USER_FONCTIONS = USER_FONCTIONS.map((fonction) => {
  return {
    canonicalName: fonction.canonicalName,
    normalizedSynonyms: fonction.synonyms.map((syn) => normalizeString(syn)),
  };
});
