export enum StructureRefusMotif {
  COMPTE_EXISTANT = "COMPTE_EXISTANT",
  PAS_DE_DOMICILIATION = "PAS_DE_DOMICILIATION",
  ERREUR_DOMICILIE = "ERREUR_DOMICILIE",
}

export enum StructureSuppressionMotif {
  COMPTE_EXISTANT = "COMPTE_EXISTANT",
  PAS_DE_DOMICILIATION = "PAS_DE_DOMICILIATION",
  PLUS_UTILISATION = "PLUS_UTILISATION",
  INACTIF = "INACTIF",
}
