
mongodbDatabase: domifa
mongodbPassword: ${MONGODB_PASSWORD}
mongodbUsername: domifa

mongodbRootPassword: ${MONGODB_ROOT_PASSWORD}

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 128Mi

persistence:
  enabled: false
