// French labels for app_log actions, used by the user activity tab. Keep keys
// in sync with backend `LogAction.type.ts` — missing keys fall back to the
// raw code so a new action is still visible (just not translated).
export const LOG_ACTION_LABELS: Record<string, string> = {
  ADMIN_CREATE_USER_STRUCTURE: "Création d'un utilisateur de structure",
  ADMIN_CREATE_USER_SUPERVISOR: "Création d'un utilisateur pilotage",
  ADMIN_PATCH_USER_SUPERVISOR: "Modification d'un utilisateur pilotage",
  ADMIN_DELETE_USER_SUPERVISOR: "Suppression d'un utilisateur pilotage",
  ADMIN_ELEVATE_ROLE_USER_SUPERVISOR: "Promotion en administrateur",
  ADMIN_USER_ROLE_CHANGE: "Changement de rôle utilisateur",
  ADMIN_USER_CREATE: "Création d'un utilisateur",
  ADMIN_USER_DELETE: "Suppression d'un utilisateur",
  ADMIN_PASSWORD_RESET: "Réinitialisation de mot de passe (admin)",
  ADMIN_STRUCTURE_VALIDATE: "Validation d'une structure",
  ADMIN_STRUCTURE_DELETE: "Suppression d'une structure",
  ADMIN_STRUCTURE_REFUSAL: "Refus d'une structure",
  ADMIN_STRUCTURE_CREATION: "Création d'une structure",
  USER_CREATE: "Création d'un utilisateur",
  USER_DELETE: "Suppression d'un utilisateur",
  USER_ROLE_CHANGE: "Changement de rôle",
  EXPORT_DOMIFA: "Export DomiFa",
  EXPORT_STATS: "Export des statistiques",
  EXPORT_STATS_FROM_ADMIN: "Export des statistiques (admin)",
  EXPORT_USAGERS: "Export des usagers",
  GET_STATS: "Consultation des statistiques",
  GET_STATS_PORTAIL_ADMIN: "Consultation des statistiques (pilotage)",
  GET_STATS_PORTAIL_ADMIN_DENIED: "Accès statistiques refusé",
  EXPORT_STATS_PORTAIL_ADMIN: "Export des statistiques (pilotage)",
  IMPORT_USAGERS_SUCCESS: "Import d'usagers réussi",
  IMPORT_USAGERS_PREVIEW: "Aperçu d'import d'usagers",
  IMPORT_USAGERS_FAILED: "Import d'usagers échoué",
  IMPORT_TEMPLATE_DOWNLOAD: "Téléchargement du modèle d'import",
  IMPORT_DOWNLOAD_GUIDE: "Téléchargement du guide d'import",
  REACTIVATION_ACCOUNT: "Réactivation du compte",
  REACTIVATION_STRUCTURE: "Réactivation de la structure",
  BREVO_SYNC: "Synchronisation Brevo",
  STRUCTURE_UPDATE: "Mise à jour de la structure",
  USAGERS_DELETE: "Suppression d'usagers",
  USAGERS_PHONE_UPDATE: "Mise à jour du téléphone usager",
  USAGERS_PHONE_DELETE: "Suppression du téléphone usager",
  USAGERS_EMAIL_UPDATE: "Mise à jour de l'email usager",
  USAGERS_EMAIL_DELETE: "Suppression de l'email usager",
  USAGERS_DOCS_UPLOAD: "Téléversement d'un document usager",
  USAGERS_DOCS_DOWNLOAD: "Téléchargement d'un document usager",
  USAGERS_DOCS_DELETE: "Suppression d'un document usager",
  USAGERS_DOCS_RENAME: "Renommage d'un document usager",
  USAGERS_DOCS_SHARED: "Partage d'un document usager",
  USAGERS_ENABLE_SMS: "Activation des SMS usager",
  USAGERS_DISABLE_SMS: "Désactivation des SMS usager",
  ENABLE_SMS_BY_STRUCTURE: "Activation des SMS (structure)",
  DISABLE_SMS_BY_STRUCTURE: "Désactivation des SMS (structure)",
  SMS_SETTINGS_UPDATE: "Mise à jour des paramètres SMS",
  MON_DOMIFA_DOWNLOAD_DOC: "Téléchargement d'un document Mon DomiFa",
  MON_DOMIFA_DOWNLOAD_DOC_TRY: "Tentative de téléchargement Mon DomiFa",
  MON_DOMIFA_CREATE_PORTAIL_ACCOUNT_BULK: "Création de comptes portail (bulk)",
  THROTTLE_BLOCKED: "Quota de requêtes dépassé",
  REQUEST_BLOCKED: "Requête bloquée",
  UNBLOCK_USER: "Déblocage d'un utilisateur",
  BLOCK_USER: "Blocage automatique d'un utilisateur",
  BLOCK_USER_BY_ADMIN: "Blocage manuel d'un utilisateur",
  ACCESS_DENIED_NON_ACTIVE: "Accès refusé (compte non actif)",
};

export function getLogActionLabel(action: string): string {
  return LOG_ACTION_LABELS[action] ?? action;
}
