global:
  pgSecretName: pg-app

backend:
  ~chart: app
  ~needs: [backend-cron]
  imagePackage: backend
  host: "api-{{ .Values.global.host }}"
  probesPath: /healthz
  containerPort: 3000
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits: # exports need a lot of CPU/RAM ATM
      cpu: 3
      memory: 3Gi
  startupProbe:
    httpGet:
      path: /healthz
      port: http
      scheme: HTTP
    initialDelaySeconds: 30
    failureThreshold: 50
    periodSeconds: 10
  livenessProbe:
    failureThreshold: 20
    httpGet:
      path: /healthz
      port: http
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
    - secretRef:
        name: domifa-encryption-key
  vars: &backendVars
    TZ: Europe/Paris
    POSTGRES_HOST: "$(PGHOST)"
    POSTGRES_USERNAME: "$(PGUSER)"
    POSTGRES_PASSWORD: "$(PGPASSWORD)"
    POSTGRES_DATABASE: "$(PGDATABASE)"
    POSTGRES_PORT: "$(PGPORT)"
    DOMIFA_BACKEND_URL: "https://api-{{ .Values.global.host }}/"
    DOMIFA_FRONTEND_URL: "https://{{ .Values.global.host }}/"
    DOMIFA_PORTAIL_USAGERS_URL: "https://mon-{{ .Values.global.host }}/"
    DOMIFA_PORTAIL_ADMINS_URL: "https://admin-{{ .Values.global.host }}/"
    DOMIFA_CRON_ENABLED: "false"
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000

backend-export:
  # duplicate keys
  ~chart: app
  ~needs: [backend-cron]
  imagePackage: backend
  host: "api-{{ .Values.global.host }}"
  probesPath: /healthz
  containerPort: 3000
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-keepalive-requests: "100"
      nginx.ingress.kubernetes.io/proxy-keepalive-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  resources:
    requests:
      cpu: 0.3
      memory: 512Mi
    limits: # exports need a lot of CPU/RAM ATM
      cpu: 3
      memory: 3Gi
  startupProbe:
    httpGet:
      path: /healthz
      port: http
      scheme: HTTP
    initialDelaySeconds: 30
    failureThreshold: 50
    periodSeconds: 10
  livenessProbe:
    failureThreshold: 20
    httpGet:
      path: /healthz
      port: http
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
    - secretRef:
        name: domifa-encryption-key
  vars: &backendVars
    TZ: Europe/Paris
    POSTGRES_HOST: "$(PGHOST)"
    POSTGRES_USERNAME: "$(PGUSER)"
    POSTGRES_PASSWORD: "$(PGPASSWORD)"
    POSTGRES_DATABASE: "$(PGDATABASE)"
    POSTGRES_PORT: "$(PGPORT)"
    DOMIFA_BACKEND_URL: "https://api-{{ .Values.global.host }}/"
    DOMIFA_FRONTEND_URL: "https://{{ .Values.global.host }}/"
    DOMIFA_PORTAIL_USAGERS_URL: "https://mon-{{ .Values.global.host }}/"
    DOMIFA_PORTAIL_ADMINS_URL: "https://admin-{{ .Values.global.host }}/"
    DOMIFA_CRON_ENABLED: "false"
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000

  # new keys
  ingress:
    paths:
      - /export
      - /stats
      - /stats/home
      - /admin/structures/export

backend-cron:
  ~chart: app
  ~needs: [build-backend]
  imagePackage: backend
  .ingress.enabled: false
  probesPath: /healthz
  containerPort: 3000
  resources:
    requests:
      cpu: 0.2
      memory: 256Mi
    limits:
      cpu: 1.5
      memory: 2Gi
  startupProbe:
    httpGet:
      path: /healthz
      port: http
      scheme: HTTP
    initialDelaySeconds: 30
    failureThreshold: 100
    periodSeconds: 60
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
  vars:
    <<: *backendVars
    DOMIFA_CRON_ENABLED: "true"

  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000

frontend:
  ~chart: app
  ~needs: [build-frontend]
  imagePackage: frontend
  host: "{{ .Values.global.host }}"
  containerPort: 8080
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Content-Security-Policy: default-src 'none'; manifest-src 'self' https://*.gouv.fr; connect-src 'self' https://*.gouv.fr ; media-src 'self' https://domifaprod2.blob.core.windows.net/ https://tally.so/; font-src 'self'; img-src 'self' https://tally.so/ data:; script-src 'self' 'unsafe-inline' https://*.gouv.fr https://tally.so/ https://tally.so/widgets/embed.js ; frame-src 'self' https://*.gouv.fr  https://tally.so/ ; style-src 'self' 'unsafe-inline'";
        more_set_headers "X-Frame-Options: deny";
        more_set_headers "X-Content-Type-Options: nosniff";
        more_set_headers "Cache-Control: no-store";
  resources:
    requests:
      cpu: 0.2
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi

  securityContext:
    fsGroup: 101
    runAsUser: 101
    runAsGroup: 101

portail-admins:
  ~chart: app
  ~needs: [build-portail-admins]
  imagePackage: portail-admins
  host: "admin-{{ .Values.global.host }}"
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Content-Security-Policy: default-src 'none'; manifest-src 'self' https://*.gouv.fr; connect-src 'self' https://*.gouv.fr; font-src 'self'; img-src 'self' data:; script-src 'self' https://*.gouv.fr 'unsafe-inline'; frame-src 'self' https://*.gouv.fr; style-src 'self' 'unsafe-inline'";
        more_set_headers "X-Frame-Options: deny";
        more_set_headers "X-Robots-Tag: noindex, nofollow, nosnippet, noarchive";
        more_set_headers "X-Content-Type-Options: nosniff";
        more_set_headers "Cache-Control: no-store";
  containerPort: 8080
  securityContext:
    fsGroup: 101
    runAsUser: 101
    runAsGroup: 101

portail-usagers:
  ~chart: app
  ~needs: [build-portail-usagers]
  imagePackage: portail-usagers
  host: "mon-{{ .Values.global.host }}"
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Content-Security-Policy: default-src 'none'; manifest-src 'self' https://*.gouv.fr; connect-src 'self' https://*.gouv.fr ; media-src 'self' https://domifaprod2.blob.core.windows.net/ https://tally.so/; font-src 'self'; img-src 'self' https://tally.so/ data:; script-src 'self' 'unsafe-inline' https://*.gouv.fr https://tally.so/ https://tally.so/widgets/embed.js ; frame-src 'self' https://*.gouv.fr  https://tally.so/ ; style-src 'self' 'unsafe-inline'";
        more_set_headers "X-Frame-Options: deny";
        more_set_headers "X-Content-Type-Options: nosniff";
        more_set_headers "Cache-Control: no-store";
  containerPort: 8080
  securityContext:
    fsGroup: 101
    runAsUser: 101
    runAsGroup: 101

jobs:
  runs:
    build-backend:
      use: build
      with:
        imagePackage: backend
        dockerfile: packages/backend/Dockerfile
        buildArgs:
          DOMIFA_ENV_ID: "{{ .Values.global.env }}"

    build-frontend:
      use: build
      with:
        imagePackage: frontend
        dockerfile: packages/frontend/Dockerfile
        buildArgs:
          DOMIFA_ENV_ID: "{{ .Values.global.env }}"
          DOMIFA_BACKEND_URL: "https://api-{{ .Values.global.host }}/"
          DOMIFA_PORTAIL_ADMINS_URL: "https://admin-{{ .Values.global.host }}/"
          DOMIFA_PORTAIL_USAGERS_URL: "https://mon-{{ .Values.global.host }}/"
          DOMIFA_FRONTEND_URL: "https://{{ .Values.global.host }}/"
          DOMIFA_FRONTEND_META_ROBOTS: noindex,nofollow
          DOMIFA_SENTRY_DSN_FRONTEND: "https://5dab749719e9488798341efad0947291@sentry.fabrique.social.gouv.fr/31"

    build-portail-admins:
      use: build
      with:
        imagePackage: portail-admins
        dockerfile: packages/portail-admins/Dockerfile
        buildArgs:
          DOMIFA_ENV_ID: "{{ .Values.global.env }}"
          DOMIFA_BACKEND_URL: "https://api-{{ .Values.global.host }}/"
          DOMIFA_FRONTEND_URL: "https://{{ .Values.global.host }}/"
          DOMIFA_SENTRY_DSN_PORTAIL_ADMIN: "https://5dab749719e9488798341efad0947291@sentry.fabrique.social.gouv.fr/31"

    build-portail-usagers:
      use: build
      with:
        imagePackage: portail-usagers
        dockerfile: packages/portail-usagers/Dockerfile
        buildArgs:
          DOMIFA_ENV_ID: "{{ .Values.global.env }}"
          DOMIFA_BACKEND_URL: "https://api-{{ .Values.global.host }}/"
          DOMIFA_SENTRY_DSN_PORTAIL: "https://904877ea9ec4454aa1be7b629a6ea340@sentry.fabrique.social.gouv.fr/58"
          DOMIFA_FRONTEND_META_ROBOTS: noindex,nofollow
