export enum StructureWaitingTime {
  ONE_WEEK = "ONE_WEEK",
  TWO_WEEKS = "TWO_WEEKS",
  ONE_MONTH = "ONE_MONTH",
  ONE_TO_SIX_MONTHS = "ONE_TO_SIX_MONTHS",
  MORE_THAN_SIX_MONTHS = "MORE_THAN_SIX_MONTHS",
}
