import { UsagerCerfaFields } from "../../../constants/cerfa";
import { CerfaTypeDom } from "../CerfaTypeDom.enum";

export const CERFA_MOCK_USAGER_ACTIF: UsagerCerfaFields = {
  adresse: "CCAS de Test\n1 rue de l'océan\n92600 - Asnieres-sur-seine",
  adresseOrga1: "1 rue de l'océan\n92600 - Asnieres-sur-seine",
  agrement: null,
  anneeDebut: "2019",
  anneeDecision1A: "2023",
  anneeDecision1B: "2023",
  anneeDecision2: "2023",
  anneeFin: "2020",
  anneeNaissance1: "1998",
  anneeNaissance2: "1998",
  anneePremiereDom: "2018",
  anneeRdv: "",
  ayantsDroits: "Karamoko Mauricette né(e) le 20/12/1978",
  courriel: "domicilie2@yopmail.com",
  courrielOrga: "ccas.test@yopmail.com",
  decision: "",
  entretienAdresse: "1 rue de l'océan\n92600 - Asnieres-sur-seine",
  entretienAvec: "",
  heureRdv: "",
  jourDebut: "12",
  jourDecision1A: "22",
  jourDecision1B: "22",
  jourDecision2: "22",
  jourFin: "12",
  jourNaissance1: "07",
  jourNaissance2: "07",
  jourPremiereDom: "11",
  jourRdv: "",
  lieuNaissance1: "BOUAKÉ, CÔTE D'IVOIRE",
  lieuNaissance2: "BOUAKÉ, CÔTE D'IVOIRE",
  minutesRdv: "",
  moisDebut: "02",
  moisDecision1A: "03",
  moisDecision1B: "03",
  moisDecision2: "03",
  moisFin: "02",
  moisNaissance1: "08",
  moisNaissance2: "08",
  moisPremiereDom: "01",
  moisRdv: "",
  motifRefus: "",
  nomOrga1: "CCAS DE TEST",
  nomOrga2: "CCAS DE TEST",
  noms1: "KARAMOKO",
  noms2: "KARAMOKO",
  numeroUsager: "63",
  orientation: "",
  prefecture1: "",
  prefecture2: "",
  prenoms1: "MAURICE",
  prenoms2: "MAURICE",
  rattachement: "",
  responsable: "JEAN, THOMSON, PDG",
  sexe1: "2",
  sexe2: "2",
  signature1A: "ASNIERES-SUR-SEINE",
  signature1B: "ASNIERES-SUR-SEINE",
  signature2: "ASNIERES-SUR-SEINE",
  telephone: "06 06 06 06 06",
  telephoneOrga: "06 02 03 04 05",
  typeDemande: CerfaTypeDom.RENOUVELLEMENT,
};

export const CERFA_MOCK_USAGER_REFUS: UsagerCerfaFields = {
  adresse: "CCAS de Test\n1 rue de l'océan\n92600 - Asnieres-sur-seine",
  adresseOrga1: "1 rue de l'océan\n92600 - Asnieres-sur-seine",
  agrement: null,
  anneeDebut: "2019",
  anneeDecision1A: "2023",
  anneeDecision1B: "2023",
  anneeDecision2: "2023",
  anneeFin: "2020",
  anneeNaissance1: "1940",
  anneeNaissance2: "1940",
  anneePremiereDom: "2019",
  anneeRdv: "",
  ayantsDroits: "",
  courriel: "",
  courrielOrga: "ccas.test@yopmail.com",
  decision: "2",
  entretienAdresse: "1 rue de l'océan\n92600 - Asnieres-sur-seine",
  entretienAvec: "",
  heureRdv: "",
  jourDebut: "12",
  jourDecision1A: "22",
  jourDecision1B: "22",
  jourDecision2: "22",
  jourFin: "09",
  jourNaissance1: "07",
  jourNaissance2: "07",
  jourPremiereDom: "07",
  jourRdv: "",
  lieuNaissance1: "MACON",
  lieuNaissance2: "MACON",
  minutesRdv: "",
  moisDebut: "09",
  moisDecision1A: "03",
  moisDecision1B: "03",
  moisDecision2: "03",
  moisFin: "08",
  moisNaissance1: "08",
  moisNaissance2: "08",
  moisPremiereDom: "10",
  moisRdv: "",
  motifRefus: "Nombre maximal domiciliations atteint",
  nomOrga1: "CCAS DE TEST",
  nomOrga2: "CCAS DE TEST",
  noms1: "DUPONT",
  noms2: "DUPONT",
  numeroUsager: "3",
  orientation: "",
  prefecture1: "",
  prefecture2: "",
  prenoms1: "FRED",
  prenoms2: "FRED",
  rattachement: "",
  responsable: "JEAN, THOMSON, PDG",
  sexe1: "2",
  sexe2: "2",
  signature1A: "ASNIERES-SUR-SEINE",
  signature1B: "ASNIERES-SUR-SEINE",
  signature2: "ASNIERES-SUR-SEINE",
  telephone: "",
  telephoneOrga: "06 02 03 04 05",
  typeDemande: CerfaTypeDom.PREMIERE_DEMANDE,
};
