export type LogAction =
  | "USAGERS_DOCS_UPLOAD"
  | "USAGERS_DOCS_DOWNLOAD"
  | "USAGERS_DOCS_DELETE"
  | "EXPORT_USAGERS"
  | "GET_STATS"
  | "EXPORT_STATS"
  | "ENABLE_SMS_BY_STRUCTURE"
  | "DISABLE_SMS_BY_STRUCTURE"

  // deorecated
  | "SUPPRIMER_PIECE_JOINTE"
  | "SUPPRIMER_DOMICILIE"
  | "RESET_PASSWORD_PORTAIL"
  | "DOWNLOAD_PASSWORD_PORTAIL"
  | "DELETE_NOTE"
  | "ENABLE_PORTAIL_BY_STRUCTURE"
  | "DISABLE_PORTAIL_BY_STRUCTURE";
