export type LogAction =
  // Docs
  | "USAGERS_DOCS_UPLOAD"
  | "USAGERS_DOCS_DOWNLOAD"
  | "USAGERS_DOCS_DELETE"
  | "USAGERS_DOCS_RENAME"
  | "USAGERS_DOCS_SHARED"

  ///
  | "EXPORT_USAGERS"
  | "GET_STATS"
  | "EXPORT_STATS"
  | "ENABLE_SMS_BY_STRUCTURE"
  | "DISABLE_SMS_BY_STRUCTURE"
  | "EXPORT_DOMIFA"
  | "GET_STATS_PORTAIL_ADMIN"
  | "EXPORT_STATS_PORTAIL_ADMIN"

  // deorecated
  | "SUPPRIMER_PIECE_JOINTE"
  | "SUPPRIMER_DOMICILIE"
  | "RESET_PASSWORD_PORTAIL"
  | "DOWNLOAD_PASSWORD_PORTAIL"
  | "DELETE_NOTE"
  | "ENABLE_PORTAIL_BY_STRUCTURE"
  | "DISABLE_PORTAIL_BY_STRUCTURE";
