common:
  tmp_dir: "/tmp"

log:
  level: "debug"
  format: "text"

storage:
  # type: "directory"
  directory:
    path: "/tmp/pg_dump"
  type: s3
  s3:
    endpoint: "{{bucket_endpoint}}"
    bucket: "{{bucket_name}}"
    region: "{{bucket_region}}"
    access_key_id: "{{bucket_access_key}}"
    secret_access_key: "{{bucket_secret_key}}"
    prefix: "/anonymizer/pg_dumps"
    # force_path_style: true

dump:

  transformation:
    - schema: "public"
      name: "usager"
      transformers:
        - name: "RandomBool"
          params:
            column: "migrated"
        - name: "TemplateRecord"
          params:
            columns:
              - "ayantsDroits"
            template: >
              {{ $val := .GetColumnValue "ayantsDroits" }}
              {{ $newPeople := list }}
              {{ if isNotNull $val }}
                {{ range $val }}
                  {{ $modifiedPerson := dict "lien" .lien "prenom" fakerFirstName "nom" fakerFirstLastName "dateNaissance" .dateNaissance }}
                  {{ $newPeople = append $newPeople $modifiedPerson }}
                {{ end }}
                {{ $updatedValue := toJson $newPeople }}
                {{ .SetColumnValue "ayantsDroits" $updatedValue }}
              {{ end }}