log:
  level: debug
  format: text

storage:
  type: "{{type}}"
  directory:
    path: "{{tmp}}"
  s3:
    endpoint: "{{bucket_endpoint}}"
    bucket: "{{bucket_name}}"
    region: "{{bucket_region}}"
    access_key_id: "{{bucket_access_key}}"
    secret_access_key: "{{bucket_secret_key}}"
    prefix: "/anonymizer/pg_dumps"
    # force_path_style: true

dump:
  transformation:
    - schema: public
      name: usager
      transformers:
        - name: SetNull
          params:
            column: email
        - name: RandomFirstName
          params:
            column: prenom
        - name: Json
          params:
            column: telephone
            operations:
              - operation: set
                path: countryCode
                value: fr
              - operation: set
                path: numero
                value: ""
        - name: SetNull
          params:
            column: pinnedNote
        - name: RandomLastName
          params:
            column: nom
        - name: RandomLastName
          params:
            column: surnom
            keep_null: true
        - name: RealAddress
          params:
            columns:
              - name: villeNaissance
                template: "{{.City}}"
        - name: Json
          params:
            column: decision
            operations:
              - operation: set
                path: motifDetails
                value: null
              - operation: set
                path: orientationDetails
                value: null
              - operation: set
                path: userName
                value_template: "{{ quote fakerName }}"
              - operation: set
                path: userId
                value_template: "{{ randomInt 0 1000000000}}"
              - operation: set
                path: uuid
                value_template: "{{ quote fakerUUID }}"
        - name: "Cmd"
          # --- historique
          params:
            driver:
              name: "json"
            validate: true
            timeout: 3600s
            executable: "node"
            args:
              - "./dist/usager--historique.js"
            columns:
              - name: "historique"
                skip_on_null_input: true
        - name: "Cmd"
          # --- ayantsDroits
          params:
            driver:
              name: "json"
            validate: true
            timeout: 3600s
            executable: "node"
            args:
              - "./dist/usager--ayants-droits.js"
            columns:
              - name: "ayantsDroits"
                skip_on_null_input: true
        - name: "Cmd"
          # --- import
          params:
            driver:
              name: "json"
            validate: true
            timeout: 3600s
            executable: "node"
            args:
              - "./dist/usager--import.js"
            columns:
              - name: "import"
                skip_on_null_input: true
        - name: "Cmd"
          # --- rdv
          params:
            driver:
              name: "json"
            validate: true
            timeout: 3600s
            executable: "node"
            args:
              - "./dist/usager--rdv.js"
            columns:
              - name: "rdv"
                skip_on_null_input: true
        - name: Replace
          params:
            column: migrated
            value: true
            keep_null: false
        - name: "Cmd"
          # --- options
          params:
            driver:
              name: "json"
            validate: true
            timeout: 3600s
            executable: "node"
            args:
              - "./dist/usager--options.js"
            columns:
              - name: "options"
                skip_on_null_input: true

    - schema: public
      name: structure
      transformers:
        - name: "Template"
          params:
            column: "email"
            template: >
              {{ printf "structure-%d@domifa-fake.fabrique.social.gouv.fr" (.GetColumnValue "id") }}
        - name: SetNull
          params:
            column: token
        - name: SetNull
          params:
            column: tokenDelete
        - name: SetNull
          params:
            column: hardReset
        - name: Json
          params:
            column: telephone
            operations:
              - operation: set
                path: countryCode
                value: "fr"
              - operation: set
                path: numero
                value: "0600000000"
        - name: Json
          params:
            column: responsable
            operations:
              - operation: set
                path: nom
                value_template: "{{ quote fakerFirstLastName }}"
              - operation: set
                path: prenom
                value_template: "{{ quote fakerFirstName }}"

    - schema: public
      name: user_structure
      transformers:
        - name: RandomFirstName
          params:
            column: prenom
        - name: RandomLastName
          params:
            column: nom
        - name: "Cmd"
          params:
            driver:
              name: "json"
            validate: true
            timeout: 3600s
            executable: "node"
            args:
              - "./dist/user-structure--fonction.js"
            columns:
              - name: "fonction"
                skip_on_null_input: true
        - name: "Template"
          params:
            column: "email"
            template: >
              {{ printf "%s-%d-%d@domifa-fake.fabrique.social.gouv.fr" (.GetColumnValue "role") (.GetColumnValue "structureId") (.GetColumnValue "id") }}

    - schema: public
      name: interactions
      transformers:
        - name: Replace
          params:
            column: content
            value: "Random content"
        - name: "Template"
          params:
            column: "userName"
            template: >
              {{ quote fakerName }}

    - schema: public
      name: usager_options_history
      transformers:
        - name: RandomFirstName
          params:
            column: prenom
        - name: RandomLastName
          params:
            column: nom
        - name: "Template"
          params:
            column: "userName"
            template: >
              {{ quote fakerName }}
        - name: RealAddress
          params:
            columns:
              - name: adresse
                template: "{{.Address}}"

    - schema: public
      name: usager_docs
      transformers:
        - name: RandomSentence
          params:
            column: label
            keep_null: true
        - name: SetNull
          params:
            column: encryptionContext
        - name: SetNull
          params:
            column: encryptionVersion
        - name: RandomName
          params:
            column: createdBy

    - schema: public
      name: usager_entretien
      transformers:
        - name: SetNull
          params:
            column: commentaires
        - name: SetNull
          params:
            column: revenusDetail
        - name: SetNull
          params:
            column: orientationDetail
        - name: SetNull
          params:
            column: liencommuneDetail
        - name: SetNull
          params:
            column: residenceDetail
        - name: SetNull
          params:
            column: causeDetail
        - name: SetNull
          params:
            column: raisonDetail
        - name: SetNull
          params:
            column: situationProDetail
        - name: SetNull
          params:
            column: accompagnementDetail

    - schema: public
      name: user_usager
      transformers:
        - name: "Cmd"
          params:
            driver:
              name: "json"
            validate: true
            timeout: 3600s
            executable: "node"
            args:
              - "./dist/user-usager--password.js"
            columns:
              - name: "password"
                skip_on_null_input: true
        - name: Json
          params:
            column: lastPasswordResetStructureUser
            operations:
              - operation: set
                path: userId
                value: "1"
              - operation: set
                path: userName
                value: "Nom"

    - schema: public
      name: user_structure_security
      transformers:
        - name: SetNull
          params:
            column: temporaryTokens
        - name: "TemplateRecord"
          params:
            columns:
              - "eventsHistory"
            template: >
              {{ .SetColumnValue "eventsHistory" "[]" }}
            validate: true

