import { UserFonction } from "../../../users";
import { matchFonctionUtilisateur } from "../matchFonctionUtilisateur";

const TEST_MATCH = {
  "---------": UserFonction.AUTRE,
  Inconnu: UserFonction.AUTRE,
  Directrice: UserFonction.DIRECTEUR_RESPONSABLE,
  Président: UserFonction.PRESIDENT,
  Maire: UserFonction.MAIRE,
  Directeur: UserFonction.DIRECTEUR_RESPONSABLE,
  "Chef de service": UserFonction.CHEF_DE_SERVICE,
  Responsable: UserFonction.DIRECTEUR_RESPONSABLE,
  DIRECTRICE: UserFonction.DIRECTEUR_RESPONSABLE,
  Présidente: UserFonction.PRESIDENT,
  "Responsable du CCAS": UserFonction.DIRECTEUR_RESPONSABLE,
  "Agent du CCAS": UserFonction.AGENT_ACCUEIL,
  "Assistante Sociale": UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  DGS: UserFonction.DIRECTEUR_GENERAL_DES_SERVICES,
  "Responsable CCAS": UserFonction.DIRECTEUR_RESPONSABLE,
  "Adjoint administratif": UserFonction.ADJOINT_ADMINISTRATIF,
  "Agent d'accueil": UserFonction.AGENT_ACCUEIL,
  "Directeur du CCAS": UserFonction.DIRECTEUR_RESPONSABLE,
  "Président du CCAS": UserFonction.PRESIDENT,
  Secrétaire: UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Secrétaire de mairie": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "adjoint administratif": UserFonction.ADJOINT_ADMINISTRATIF,
  "Adjoint Administratif": UserFonction.ADJOINT_ADMINISTRATIF,
  "Adjointe administrative": UserFonction.ADJOINT_ADMINISTRATIF,
  "Assistante administrative": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Assistante sociale": UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  CESF: UserFonction.CONSEILLER_ECONOMIE_SOCIALE_ET_FAMILIALE,
  "CHEFFE DE SERVICE": UserFonction.CHEF_DE_SERVICE,
  "Conseillère ESF": UserFonction.CONSEILLER_ECONOMIE_SOCIALE_ET_FAMILIALE,
  DIRECTEUR: UserFonction.DIRECTEUR_RESPONSABLE,
  "Directeur des services": UserFonction.DIRECTEUR_RESPONSABLE,
  "directeur du CCAS": UserFonction.DIRECTEUR_RESPONSABLE,
  "Directrice du CCAS": UserFonction.DIRECTEUR_RESPONSABLE,
  MAIRE: UserFonction.MAIRE,
  PRESIDENT: UserFonction.PRESIDENT,
  responsable: UserFonction.DIRECTEUR_RESPONSABLE,
  RESPONSABLE: UserFonction.DIRECTEUR_RESPONSABLE,
  "SECRETAIRE DE MAIRIE": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Secrétaire de Mairie": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Secrétaire du CCAS": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Travailleur social": UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  ACCUEILLANT: UserFonction.AGENT_ACCUEIL,
  "Adjoint administratif 2ème classe": UserFonction.ADJOINT_ADMINISTRATIF,
  "Adjoint Administratif Principal": UserFonction.ADJOINT_ADMINISTRATIF,
  "adjoint administratif service ccas": UserFonction.ADJOINT_ADMINISTRATIF,
  "Adjoint Administrative": UserFonction.ADJOINT_ADMINISTRATIF,
  "Adjoint au directeur": UserFonction.ADJOINT_ADMINISTRATIF,
  "Adjointe  administrative": UserFonction.ADJOINT_ADMINISTRATIF,
  "Adjointe aux Affaires Sociales - Vice-Présidente du CCAS":
    UserFonction.ADJOINT_ADMINISTRATIF,
  agen: UserFonction.AGENT_ACCUEIL,
  "agent ": UserFonction.AGENT_ACCUEIL,
  "Agent ": UserFonction.AGENT_ACCUEIL,
  "agent administratif": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Agent Administratif": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "AGENT ADMINISTRATIF": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "AGENT ADMINSTRAITF EN CHARGE DU CCAS":
    UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Agent CCAS": UserFonction.AGENT_ACCUEIL,
  "Agent chargé des élections de domicile": UserFonction.AGENT_ACCUEIL,
  "agent d'accueil": UserFonction.AGENT_ACCUEIL,
  "Agent d'accueil administratif": UserFonction.AGENT_ACCUEIL,
  "Agent d'accueil social": UserFonction.AGENT_ACCUEIL,
  "Agent de premier accueil social": UserFonction.AGENT_ACCUEIL,
  "agent en charge du CCAS": UserFonction.AGENT_ACCUEIL,
  "Agent en charge du CCAS": UserFonction.AGENT_ACCUEIL,
  "agent social ": UserFonction.AGENT_ACCUEIL,
  "Agent social": UserFonction.AGENT_ACCUEIL,
  "Ajoint au Maire CCAS": UserFonction.ADJOINT_ADMINISTRATIF,
  "Animateur Socio Éducatif": UserFonction.MEDIATION_SOCIALE,
  "Assistant de Service Social":
    UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  Assistante: UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Assistante administrative ": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Assistante administrative CCAS logements":
    UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Assistante CCAS": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Assistante de direction": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "ASSISTANTE DE DIRECTION": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Assistante de service social":
    UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  "Assistante de Service Social LHSS Babinski":
    UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  "Assistante direction": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "assistante sociale": UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  "Assistant Social RR": UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  bénévole: UserFonction.BENEVOLE,
  "Bénévole Domiciliation": UserFonction.BENEVOLE,
  "Cadre administratif": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "cadre de santé": UserFonction.AUTRE,
  CCAS: UserFonction.AUTRE,
  "Chargé d'accueil social": UserFonction.AGENT_ACCUEIL,
  "Chargée de domiciliation": UserFonction.DOMICILIATION,
  "chef de service": UserFonction.CHEF_DE_SERVICE,
  "CHEF DE SERVICE": UserFonction.CHEF_DE_SERVICE,
  "Chef de Service logement Spécifique": UserFonction.CHEF_DE_SERVICE,
  "Conseillère municipale": UserFonction.ELU,
  "Conseillère municipale déléguée au social": UserFonction.ELU,
  "Conseillère Sociale ": UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  "Conseillere sociale - CHU Romain Rolland":
    UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  "Coordinateur Pôle Social CCAS MOULINS":
    UserFonction.CHARGE_DE_MISSION_ACTION_SOCIALE,
  "coordinatrice d'appui aux interventions sociales":
    UserFonction.CHARGE_DE_MISSION_ACTION_SOCIALE,
  "Coordinatrice de l'Accueil Social Universel":
    UserFonction.CHARGE_DE_MISSION_ACTION_SOCIALE,
  "Coordinatrice de la Politique sociale":
    UserFonction.CHARGE_DE_MISSION_ACTION_SOCIALE,
  "COORDINATRICE MEDICO SOCIALE": UserFonction.CHARGE_DE_MISSION_ACTION_SOCIALE,
  COORDONNATEUR: UserFonction.CHARGE_DE_MISSION_ACTION_SOCIALE,
  "Directeur ": UserFonction.DIRECTEUR_RESPONSABLE,
  directrice: UserFonction.DIRECTEUR_RESPONSABLE,
  "Directrice ": UserFonction.DIRECTEUR_RESPONSABLE,
  "Directrice des services": UserFonction.DIRECTEUR_RESPONSABLE,
  "Directrice des services Adultes en difficultés":
    UserFonction.DIRECTEUR_RESPONSABLE,
  "DIRECTRICE GENERALE DES SERVICES":
    UserFonction.DIRECTEUR_GENERAL_DES_SERVICES,
  "Directrice Locale de l'Action Sociale": UserFonction.DIRECTEUR_RESPONSABLE,
  Diretrice: UserFonction.DIRECTEUR_RESPONSABLE,
  Educatrice: UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  "Elue en charge du Social": UserFonction.ELU,
  Equipière: UserFonction.BENEVOLE,
  "er accueil en charge des domiciliations": UserFonction.DOMICILIATION,
  "GESTIONNAIRE SOCIALE": UserFonction.CHARGE_DE_MISSION_ACTION_SOCIALE,
  "Maire de Montélier": UserFonction.MAIRE,
  "Maire, Président du CCAS": UserFonction.MAIRE,
  null: UserFonction.AUTRE,
  PRESIDENCE: UserFonction.PRESIDENT,
  "Président CCAS": UserFonction.PRESIDENT,
  "Président du C.C.A.S.": UserFonction.PRESIDENT,
  "Président du CCAS et Maire de la commune": UserFonction.PRESIDENT,
  PRESIDENTE: UserFonction.PRESIDENT,
  "Présidente du CCAS": UserFonction.PRESIDENT,
  Référente: UserFonction.CHARGE_DE_MISSION_ACTION_SOCIALE,
  "Référente d'équipe": UserFonction.CHARGE_DE_MISSION_ACTION_SOCIALE,
  "Référente pôle action sociale":
    UserFonction.CHARGE_DE_MISSION_ACTION_SOCIALE,
  "référente sociale": UserFonction.CHARGE_DE_MISSION_ACTION_SOCIALE,
  "Référente Sociale": UserFonction.CHARGE_DE_MISSION_ACTION_SOCIALE,
  Respensable: UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable Action Sociale": UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable administrative": UserFonction.DIRECTEUR_RESPONSABLE,
  "RESPONSABLE ADMISSIONS": UserFonction.DIRECTEUR_RESPONSABLE,
  "RESPONSABLE CCAS DE GUIPRY-MESSAC": UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable d'action sociale et logement":
    UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable de la direction Animation Intergénérationnelle":
    UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable de la PAAL": UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable de l'Epicerie Solidaire": UserFonction.DIRECTEUR_RESPONSABLE,
  "responsable des affaires sociales": UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable des aides légales et extra-légales":
    UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable de service": UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable du pôle de développement social":
    UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable du Pôle Précarité": UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable du Pôle Social": UserFonction.DIRECTEUR_RESPONSABLE,
  "responsable du service action sociale du CCAS":
    UserFonction.DIRECTEUR_RESPONSABLE,
  "RESPONSABLE POLE ACTION SOCIALE ": UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable Pôle Social": UserFonction.DIRECTEUR_RESPONSABLE,
  "RESPONSABLE POLE SOCIAL ANIMATIONS": UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable Service administration générale":
    UserFonction.DIRECTEUR_RESPONSABLE,
  "Responsable Service logement": UserFonction.DIRECTEUR_RESPONSABLE,
  SECRETAIRE: UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "secrétaire accueil": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "secrétaire CCAS": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Secrétaire CCAS": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "secrétaire en charge des affaires sociales":
    UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Secrétaire Générale": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Secrétaire mairie": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "Secrétaire UL": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  "secrétariat service social": UserFonction.SECRETAIRE_ASSISTANT_ADMINISTRATIF,
  TEST: UserFonction.AUTRE,
  "Travailleur Social": UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  "TRAVAILLEUR SOCIAL": UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  "Travailleuse sociale": UserFonction.TRAVAILLEUR_SOCIAL_ASSISTANT_SOCIAL,
  "Vice-Président": UserFonction.VICE_PRESIDENT,
  "Vice président du CA du CCAS": UserFonction.VICE_PRESIDENT,
  "Vice président du C.C.A.S": UserFonction.VICE_PRESIDENT,
  "VICE PRESIDENTE ": UserFonction.VICE_PRESIDENT,
  "Vice-présidente": UserFonction.VICE_PRESIDENT,
  "Vice Présidente": UserFonction.VICE_PRESIDENT,
};

describe("matchFonctionUtilisateur", () => {
  describe("TEST_MATCH validation", () => {
    it("should match all TEST_MATCH key/value pairs", () => {
      Object.entries(TEST_MATCH).forEach(([key, expectedValue]) => {
        const result = matchFonctionUtilisateur(key);
        expect(result).toBe(expectedValue);
      });
    });
  });
});
