name: Backend Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: c-hive/gha-yarn-cache@v1
    - run: cp .env.dev.example.env .env
    - run: cp ./packages/backend/.env.backend.test.ci.example.env ./packages/backend/.env
    - run: yarn install --frozen-lockfile --prefer-offline
    - run: ./docker-compose.local.run.sh
    - run: _scripts/db/restore-database-docker.sh --db=test
    - run: cd packages/backend
    - run: yarn db:test:migrate-up
    - run: yarn test --coverage --detectOpenHandles --forceExit
