name: Backend Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cp .env.dev.example.env .env
    - run: cp ./packages/backend/.env.backend.test.local.example.env ./packages/backend/.env
    - run: yarn install --frozen-lockfile --prefer-offline
    - run: ./docker-compose.local.run.sh
    - run: yarn workspace @domifa/backend test:ci --coverage --detectOpenHandles --forceExit
