name: Release

# on:
#   push:
#     branches: [master, alpha, beta, next]
on: [deployment_status]

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    if: github.event.deployment_status.state == 'success'
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: yarn --frozen-lockfile --perfer-offline

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
        run: npx semantic-release
