name: Release

on:
  push:
    branches: [master, alpha, beta, next]

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: npx semantic-release
